In [1]:
from pathlib import Path
import pandas as pd

project_dir = Path(
    r"C:\Users\HP-ZBOOK i7\graphrag_test\pilot_01"
)

inspection_dir = project_dir / "inspection"

documents = pd.read_csv(
    inspection_dir / "08_documents_all.csv"
)

text_units = pd.read_csv(
    inspection_dir / "09_text_units_all.csv"
)

entities = pd.read_csv(
    inspection_dir / "01_entities_all.csv"
)

relationships = pd.read_csv(
    inspection_dir / "04_relationships_all.csv"
)

community_reports = pd.read_csv(
    inspection_dir / "07_community_reports_all.csv"
)

print("Documents:", len(documents))
print("Text units:", len(text_units))
print("Entities:", len(entities))
print("Relationships:", len(relationships))
print("Community reports:", len(community_reports))

Documents: 1
Text units: 17
Entities: 312
Relationships: 414
Community reports: 62

In [2]:
source_facts = [
    # ---------------------------------------------------------
    # POLICY AND REGULATORY FACTS
    # ---------------------------------------------------------
    {
        "fact_id": "P01",
        "category": "POLICY",
        "source_section": "Section 2 — Introduction",
        "source_fact": (
            "The Renewable Expansion Act establishes that total electricity "
            "consumption should be covered nationally and on balance by "
            "100% renewable energy from 2030."
        ),
        "expected_entities": "Austria; Renewable Expansion Act; Renewable Electricity 2030",
        "expected_relationship": (
            "Austria HAS_TARGET 100% nationally balanced renewable electricity by 2030"
        ),
    },
    {
        "fact_id": "P02",
        "category": "POLICY",
        "source_section": "Section 2 — Introduction",
        "source_fact": (
            "The Renewable Expansion Act provides for at least 11 TWh of "
            "additional photovoltaic generation by 2030 compared with 2020."
        ),
        "expected_entities": "Renewable Expansion Act; Photovoltaics; 11 TWh; 2030",
        "expected_relationship": (
            "Renewable Expansion Act HAS_TARGET 11 TWh of additional PV generation by 2030"
        ),
    },
    {
        "fact_id": "P03",
        "category": "POLICY",
        "source_section": "Section 2 — Introduction",
        "source_fact": (
            "RED III raises the EU renewable-energy share target to 42.5%, "
            "with 45% to be aimed for, by 2030."
        ),
        "expected_entities": "RED III; European Union; 42.5%; 45%; 2030",
        "expected_relationship": "RED III HAS_TARGET EU renewable-energy share by 2030",
    },
    {
        "fact_id": "P04",
        "category": "POLICY",
        "source_section": "Sections 2 and 6.3",
        "source_fact": (
            "Austria introduced a zero-percent VAT measure for eligible "
            "PV systems with a capacity of up to 35 kWp."
        ),
        "expected_entities": "VAT Exemption; PV System; 35 kWp",
        "expected_relationship": "VAT Exemption SUPPORTS PV System up to 35 kWp",
    },
    {
        "fact_id": "P05",
        "category": "POLICY",
        "source_section": "Sections 6.1 and 6.2",
        "source_fact": (
            "The proposed Electricity Industry Act includes simplified grid "
            "connection for small systems and greater transparency concerning "
            "grid capacities and development plans."
        ),
        "expected_entities": "Electricity Industry Act; Grid Connection; Grid Capacity",
        "expected_relationship": (
            "Electricity Industry Act SUPPORTS simplified and transparent grid connection"
        ),
    },
    {
        "fact_id": "P06",
        "category": "POLICY",
        "source_section": "Section 6.1",
        "source_fact": (
            "The planned Renewable Expansion Acceleration Act is intended to "
            "accelerate procedures for PV installations and required infrastructure."
        ),
        "expected_entities": (
            "Renewable Expansion Acceleration Act; PV Installation; Infrastructure"
        ),
        "expected_relationship": (
            "Renewable Expansion Acceleration Act SUPPORTS accelerated permitting"
        ),
    },
    {
        "fact_id": "P07",
        "category": "POLICY",
        "source_section": "Section 6.1",
        "source_fact": (
            "Building law, spatial planning and nature conservation are primarily "
            "responsibilities of the Austrian federal states."
        ),
        "expected_entities": (
            "Federal States; Building Law; Spatial Planning; Nature Conservation"
        ),
        "expected_relationship": (
            "Federal States IMPLEMENT policy in building, spatial-planning and conservation areas"
        ),
    },
    {
        "fact_id": "P08",
        "category": "POLICY",
        "source_section": "Section 6.1",
        "source_fact": (
            "The Federal-State Dialogue on Renewable Energy coordinates federal "
            "and state targets, land availability, processes and support strategies."
        ),
        "expected_entities": (
            "Federal-State Dialogue on Renewable Energy; Federal Government; Federal States"
        ),
        "expected_relationship": (
            "Federal-State Dialogue COORDINATES renewable-energy implementation"
        ),
    },
    {
        "fact_id": "P09",
        "category": "POLICY",
        "source_section": "Section 6.1",
        "source_fact": (
            "The 2022 amendment to the Condominium Act made the construction "
            "of PV systems on terraced houses and individual buildings easier."
        ),
        "expected_entities": "Condominium Act Amendment 2022; PV Systems; Buildings",
        "expected_relationship": (
            "Condominium Act Amendment SUPPORTS residential PV installation"
        ),
    },
    {
        "fact_id": "P10",
        "category": "POLICY",
        "source_section": "Section 2 — Introduction",
        "source_fact": (
            "The Austrian Photovoltaic Strategy is intended to be a living "
            "document that is adjusted when conditions change."
        ),
        "expected_entities": "Austrian Photovoltaic Strategy; Changing Conditions",
        "expected_relationship": (
            "Austrian Photovoltaic Strategy EVOLVES_WITH changing conditions"
        ),
    },

    # ---------------------------------------------------------
    # MARKET AND NUMERICAL FACTS
    # ---------------------------------------------------------
    {
        "fact_id": "M01",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 2 — Introduction",
        "source_fact": "Austria reached 6.3 TWh of PV generation in 2023.",
        "expected_entities": "Austria; PV Generation; 6.3 TWh; 2023",
        "expected_relationship": "Austria MEASURED_BY 6.3 TWh PV generation in 2023",
    },
    {
        "fact_id": "M02",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 4 — PV Expansion Potential",
        "source_fact": (
            "Approximately 2.5 GW of new photovoltaic capacity was installed "
            "in Austria in 2023."
        ),
        "expected_entities": "Austria; Annual PV Expansion; 2.5 GW; 2023",
        "expected_relationship": "Annual PV Expansion MEASURED_BY 2.5 GW in 2023",
    },
    {
        "fact_id": "M03",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 4 — PV Expansion Potential",
        "source_fact": (
            "One GW of new photovoltaic capacity was installed in Austria in 2022."
        ),
        "expected_entities": "Austria; Annual PV Expansion; 1 GW; 2022",
        "expected_relationship": "Annual PV Expansion MEASURED_BY 1 GW in 2022",
    },
    {
        "fact_id": "M04",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 4 — PV Expansion Potential",
        "source_fact": (
            "The Integrated Austrian Network Infrastructure Plan identifies "
            "41 TWh of photovoltaic generation potential by 2040."
        ),
        "expected_entities": "Network Infrastructure Plan; Photovoltaics; 41 TWh; 2040",
        "expected_relationship": "Network Infrastructure Plan HAS_TARGET 41 TWh PV by 2040",
    },
    {
        "fact_id": "M05",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 4 — PV Expansion Potential",
        "source_fact": (
            "At least approximately 15 TWh of the 2040 PV potential is considered "
            "achievable on existing and new buildings."
        ),
        "expected_entities": "Buildings; PV Potential; 15 TWh; 2040",
        "expected_relationship": "Buildings CONTRIBUTE_TO 15 TWh PV potential by 2040",
    },
    {
        "fact_id": "M06",
        "category": "MARKET_NUMERICAL",
        "source_section": "Sections 4 and 5",
        "source_fact": (
            "An average expansion rate of approximately 2 GW per year is needed "
            "to reach the 2040 PV potential."
        ),
        "expected_entities": "Annual PV Expansion; 2 GW per year; 2040",
        "expected_relationship": "PV Expansion HAS_TARGET approximately 2 GW per year",
    },
    {
        "fact_id": "M07",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 4 — PV Expansion Potential",
        "source_fact": (
            "The Transition 2040 scenario requires 21 TWh of photovoltaic "
            "electricity generation in 2030."
        ),
        "expected_entities": "Transition 2040; Photovoltaics; 21 TWh; 2030",
        "expected_relationship": "Transition 2040 HAS_TARGET 21 TWh PV generation in 2030",
    },
    {
        "fact_id": "M08",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 4 — PV Expansion Potential",
        "source_fact": (
            "The 21 TWh requirement for 2030 represents an increase of "
            "19 TWh compared with 2020."
        ),
        "expected_entities": "PV Expansion; 19 TWh; 2020; 2030",
        "expected_relationship": "PV Expansion MEASURED_BY 19 TWh increase from 2020 to 2030",
    },
    {
        "fact_id": "M09",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 2 — Introduction",
        "source_fact": (
            "Approximately EUR 600 million was provided for PV expansion in "
            "2023 through the Renewable Expansion Act and Climate and Energy Fund."
        ),
        "expected_entities": (
            "Renewable Expansion Act; Climate and Energy Fund; EUR 600 million; 2023"
        ),
        "expected_relationship": (
            "Renewable Expansion Act and Climate and Energy Fund SUPPORT PV expansion"
        ),
    },
    {
        "fact_id": "M10",
        "category": "MARKET_NUMERICAL",
        "source_section": "Section 4 — PV Expansion Potential",
        "source_fact": (
            "At the end of 2023, PV supplied almost 10% of Austria's final "
            "electricity consumption and approximately 2% of total energy demand."
        ),
        "expected_entities": (
            "Photovoltaics; Final Electricity Consumption; Energy Demand; 10%; 2%; 2023"
        ),
        "expected_relationship": "Photovoltaics MEASURED_BY electricity and energy shares in 2023",
    },

    # ---------------------------------------------------------
    # TECHNICAL AND IMPLEMENTATION FACTS
    # ---------------------------------------------------------
    {
        "fact_id": "T01",
        "category": "TECHNICAL",
        "source_section": "Section 6.2 — Energy Infrastructure",
        "source_fact": (
            "Digitalization of the distribution grid is important for integrating "
            "renewable and decentralized electricity."
        ),
        "expected_entities": "Distribution Grid; Digitalization; Renewable Electricity",
        "expected_relationship": "Digitalization SUPPORTS renewable-electricity grid integration",
    },
    {
        "fact_id": "T02",
        "category": "TECHNICAL",
        "source_section": "Section 6.2 — Energy Infrastructure",
        "source_fact": (
            "Photovoltaic generation peaks can no longer always be completely "
            "absorbed by the public electricity grid."
        ),
        "expected_entities": "PV Generation Peaks; Public Electricity Grid",
        "expected_relationship": "Public Electricity Grid CONSTRAINS PV generation peaks",
    },
    {
        "fact_id": "T03",
        "category": "TECHNICAL",
        "source_section": "Section 6.2 — Energy Infrastructure",
        "source_fact": (
            "Smart local energy management and storage can manage generation "
            "and consumption peaks and increase self-consumption."
        ),
        "expected_entities": "Energy Management; Energy Storage; Self-Consumption",
        "expected_relationship": (
            "Energy Management and Storage SUPPORT peak management and self-consumption"
        ),
    },
    {
        "fact_id": "T04",
        "category": "TECHNICAL",
        "source_section": "Section 6.2 — Energy Infrastructure",
        "source_fact": (
            "PV should operate synergistically with electric mobility, heat pumps, "
            "hydrogen and other generation and storage technologies."
        ),
        "expected_entities": "Photovoltaics; E-Mobility; Heat Pumps; Hydrogen; Storage",
        "expected_relationship": "Photovoltaics INTEGRATES_WITH other energy technologies",
    },
    {
        "fact_id": "T05",
        "category": "TECHNICAL",
        "source_section": "Section 6.2 — Energy Infrastructure",
        "source_fact": (
            "East-west-oriented and vertical PV installations can provide "
            "higher PV yields during shoulder and winter periods."
        ),
        "expected_entities": "East-West PV; Vertical PV; Winter Yield",
        "expected_relationship": "PV Orientation CONTRIBUTES_TO broader generation periods",
    },
    {
        "fact_id": "T06",
        "category": "TECHNICAL",
        "source_section": "Sections 6.1 and 6.4",
        "source_fact": (
            "Agri-PV enables combined agricultural and photovoltaic use and "
            "can increase land-use efficiency."
        ),
        "expected_entities": "Agri-PV; Agriculture; Land-Use Efficiency",
        "expected_relationship": "Agri-PV CONTRIBUTES_TO agricultural dual use",
    },
    {
        "fact_id": "T07",
        "category": "TECHNICAL",
        "source_section": "Section 6.4 — Acceptance",
        "source_fact": (
            "Open-space PV installations should be designed as biodiversity "
            "installations in accordance with defined ecological criteria."
        ),
        "expected_entities": "Open-Space PV; Biodiversity PV; Ecological Criteria",
        "expected_relationship": "Open-Space PV IMPLEMENTS biodiversity criteria",
    },
    {
        "fact_id": "T08",
        "category": "TECHNICAL",
        "source_section": "Section 6.4 — Acceptance",
        "source_fact": (
            "PV systems should be installed on federal buildings wherever "
            "technically and economically possible."
        ),
        "expected_entities": "Federal Buildings; PV Systems; Technical Feasibility; Economic Feasibility",
        "expected_relationship": "Federal Buildings SUPPORT PV deployment when feasible",
    },
    {
        "fact_id": "T09",
        "category": "TECHNICAL",
        "source_section": "Section 6.7 — Participation",
        "source_fact": (
            "Energy communities should be further developed using storage, "
            "consumption flexibility, real-time monitoring and control."
        ),
        "expected_entities": (
            "Energy Communities; Storage; Flexibility; Real-Time Monitoring"
        ),
        "expected_relationship": (
            "Storage and Flexibility SUPPORT development of Energy Communities"
        ),
    },
    {
        "fact_id": "T10",
        "category": "TECHNICAL",
        "source_section": "Section 6.6 — Research and Innovation",
        "source_fact": (
            "PV research should address resource efficiency, durability, "
            "repairability, reuse and recycling of PV components."
        ),
        "expected_entities": (
            "PV Research; Resource Efficiency; Durability; Repair; Reuse; Recycling"
        ),
        "expected_relationship": "PV Research CONTRIBUTES_TO PV circular economy",
    },
]

recall_checklist = pd.DataFrame(source_facts)

# Empty audit columns to be completed during tracing
recall_checklist["text_unit_capture"] = ""
recall_checklist["entity_capture"] = ""
recall_checklist["relationship_capture"] = ""
recall_checklist["community_report_capture"] = ""
recall_checklist["overall_classification"] = ""
recall_checklist["audit_notes"] = ""

print("Number of source facts:", len(recall_checklist))
print()
print("Facts by category:")
print(recall_checklist["category"].value_counts())

recall_checklist[
    [
        "fact_id",
        "category",
        "source_section",
        "source_fact",
        "expected_entities",
        "expected_relationship",
    ]
]

Number of source facts: 30

Facts by category:
category
POLICY              10
MARKET_NUMERICAL    10
TECHNICAL           10
Name: count, dtype: int64

,fact_id,category,source_section,source_fact,expected_entities,expected_relationship
0,P01,POLICY,Section 2 — Introduction,The Renewable Expansion Act establishes that t...,Austria; Renewable Expansion Act; Renewable El...,Austria HAS_TARGET 100% nationally balanced re...
1,P02,POLICY,Section 2 — Introduction,The Renewable Expansion Act provides for at le...,Renewable Expansion Act; Photovoltaics; 11 TWh...,Renewable Expansion Act HAS_TARGET 11 TWh of a...
2,P03,POLICY,Section 2 — Introduction,RED III raises the EU renewable-energy share t...,RED III; European Union; 42.5%; 45%; 2030,RED III HAS_TARGET EU renewable-energy share b...
3,P04,POLICY,Sections 2 and 6.3,Austria introduced a zero-percent VAT measure ...,VAT Exemption; PV System; 35 kWp,VAT Exemption SUPPORTS PV System up to 35 kWp
4,P05,POLICY,Sections 6.1 and 6.2,The proposed Electricity Industry Act includes...,Electricity Industry Act; Grid Connection; Gri...,Electricity Industry Act SUPPORTS simplified a...
5,P06,POLICY,Section 6.1,The planned Renewable Expansion Acceleration A...,Renewable Expansion Acceleration Act; PV Insta...,Renewable Expansion Acceleration Act SUPPORTS ...
6,P07,POLICY,Section 6.1,"Building law, spatial planning and nature cons...",Federal States; Building Law; Spatial Planning...,"Federal States IMPLEMENT policy in building, s..."
7,P08,POLICY,Section 6.1,The Federal-State Dialogue on Renewable Energy...,Federal-State Dialogue on Renewable Energy; Fe...,Federal-State Dialogue COORDINATES renewable-e...
8,P09,POLICY,Section 6.1,The 2022 amendment to the Condominium Act made...,Condominium Act Amendment 2022; PV Systems; Bu...,Condominium Act Amendment SUPPORTS residential...
9,P10,POLICY,Section 2 — Introduction,The Austrian Photovoltaic Strategy is intended...,Austrian Photovoltaic Strategy; Changing Condi...,Austrian Photovoltaic Strategy EVOLVES_WITH ch...
10,M01,MARKET_NUMERICAL,Section 2 — Introduction,Austria reached 6.3 TWh of PV generation in 2023.,Austria; PV Generation; 6.3 TWh; 2023,Austria MEASURED_BY 6.3 TWh PV generation in 2023
11,M02,MARKET_NUMERICAL,Section 4 — PV Expansion Potential,Approximately 2.5 GW of new photovoltaic capac...,Austria; Annual PV Expansion; 2.5 GW; 2023,Annual PV Expansion MEASURED_BY 2.5 GW in 2023
12,M03,MARKET_NUMERICAL,Section 4 — PV Expansion Potential,One GW of new photovoltaic capacity was instal...,Austria; Annual PV Expansion; 1 GW; 2022,Annual PV Expansion MEASURED_BY 1 GW in 2022
13,M04,MARKET_NUMERICAL,Section 4 — PV Expansion Potential,The Integrated Austrian Network Infrastructure...,Network Infrastructure Plan; Photovoltaics; 41...,Network Infrastructure Plan HAS_TARGET 41 TWh ...
14,M05,MARKET_NUMERICAL,Section 4 — PV Expansion Potential,At least approximately 15 TWh of the 2040 PV p...,Buildings; PV Potential; 15 TWh; 2040,Buildings CONTRIBUTE_TO 15 TWh PV potential by...
15,M06,MARKET_NUMERICAL,Sections 4 and 5,An average expansion rate of approximately 2 G...,Annual PV Expansion; 2 GW per year; 2040,PV Expansion HAS_TARGET approximately 2 GW per...
16,M07,MARKET_NUMERICAL,Section 4 — PV Expansion Potential,The Transition 2040 scenario requires 21 TWh o...,Transition 2040; Photovoltaics; 21 TWh; 2030,Transition 2040 HAS_TARGET 21 TWh PV generatio...
17,M08,MARKET_NUMERICAL,Section 4 — PV Expansion Potential,The 21 TWh requirement for 2030 represents an ...,PV Expansion; 19 TWh; 2020; 2030,PV Expansion MEASURED_BY 19 TWh increase from ...
18,M09,MARKET_NUMERICAL,Section 2 — Introduction,Approximately EUR 600 million was provided for...,Renewable Expansion Act; Climate and Energy Fu...,Renewable Expansion Act and Climate and Energy...
19,M10,MARKET_NUMERICAL,Section 4 — PV Expansion Potential,"At the end of 2023, PV supplied almost 10% of ...",Photovoltaics; Final Electricity Consumption; ...,Photovoltaics MEASURED_BY electricity and ener...
20,T01,TECHNICAL,Section 6.2 — Energy Infrastructure,Digitalization of the distribution grid is imp...,Distribution Grid; Digitalization; Renewable E...,Digitalization SUPPORTS renewable-electricity ...
21,T02,TECHNICAL,Section 6.2 — Energy Infrastructure,Photovoltaic generation peaks can no longer al...,PV Generation Peaks; Public Electricity Grid,Public Electricity Grid CONSTRAINS PV generati...
22,T03,TECHNICAL,Section 6.2 — Energy Infrastructure,Smart local energy management and storage can ...,Energy Management; Energy Storage; Self-Consum...,Energy Management and Storage SUPPORT peak man...
23,T04,TECHNICAL,Section 6.2 — Energy Infrastructure,PV should operate synergistically with electri...,Photovoltaics; E-Mobility; Heat Pumps; Hydroge...,Photovoltaics INTEGRATES_WITH other energy tec...
24,T05,TECHNICAL,Section 6.2 — Energy Infrastructure,East-west-oriented and vertical PV installatio...,East-West PV; Vertical PV; Winter Yield,PV Orientation CONTRIBUTES_TO broader generati...
25,T06,TECHNICAL,Sections 6.1 and 6.4,Agri-PV enables combined agricultural and phot...,Agri-PV; Agriculture; Land-Use Efficiency,Agri-PV CONTRIBUTES_TO agricultural dual use
26,T07,TECHNICAL,Section 6.4 — Acceptance,Open-space PV installations should be designed...,Open-Space PV; Biodiversity PV; Ecological Cri...,Open-Space PV IMPLEMENTS biodiversity criteria
27,T08,TECHNICAL,Section 6.4 — Acceptance,PV systems should be installed on federal buil...,Federal Buildings; PV Systems; Technical Feasi...,Federal Buildings SUPPORT PV deployment when f...
28,T09,TECHNICAL,Section 6.7 — Participation,Energy communities should be further developed...,Energy Communities; Storage; Flexibility; Real...,Storage and Flexibility SUPPORT development of...
29,T10,TECHNICAL,Section 6.6 — Research and Innovation,PV research should address resource efficiency...,PV Research; Resource Efficiency; Durability; ...,PV Research CONTRIBUTES_TO PV circular economy

In [3]:
import re

# Distinctive German phrases expected for each source fact
fact_search_terms = {
    "P01": ["100 Prozent", "2030", "erneuerbaren Energiequellen"],
    "P02": ["11 TWh", "2030"],
    "P03": ["42,5 %", "45 %", "2030"],
    "P04": ["Umsatzsteuer", "35 kWp"],
    "P05": ["Elektrizitätswirtschaftsgesetz", "Netzkapazitäten"],
    "P06": ["Erneuerbaren-Ausbau-Beschleunigungsgesetz", "Verfahrensbeschleunigung"],
    "P07": ["Bau- und Raumordnung", "Naturschutz", "Bundesländer"],
    "P08": ["Bund-Länder-Dialog", "Förderstrategien"],
    "P09": ["Wohnungseigentumsgesetz", "Reihenhäusern"],
    "P10": ["lebendiges Dokument"],

    "M01": ["6,3 TWh", "2023"],
    "M02": ["2,5 GW", "2023"],
    "M03": ["Gigawatt Neuinstallation", "2022"],
    "M04": ["41 TWh", "2040"],
    "M05": ["15 TWh", "Gebäuden"],
    "M06": ["2 GW pro Jahr"],
    "M07": ["21 TWh", "2030"],
    "M08": ["19 TWh", "2020"],
    "M09": ["600 Mio. Euro", "2023"],
    "M10": ["knapp 10 %", "etwa 2 %"],

    "T01": ["Digitalisierung des Verteilnetzes"],
    "T02": ["Erzeugungsspitzen aus Photovoltaik", "nicht mehr vollständig"],
    "T03": ["Smartes lokales Energiemanagement", "Speicherung"],
    "T04": ["E-Mobilität", "Wärmepumpe", "Wasserstoff"],
    "T05": ["Ost-West Orientierungen", "vertikale PV-Anlagen"],
    "T06": ["Agri-PV-Anlagen", "Landnutzungseffizienz"],
    "T07": ["Freiflächenanlagen", "Biodiversitätsanlagen"],
    "T08": ["Gebäuden des Bundes", "technisch und wirtschaftlich"],
    "T09": ["Energiegemeinschaften", "Betriebsmonitoring"],
    "T10": ["Haltbarkeit", "Reparaturmöglichkeit", "Wiederverwertung"],
}


def normalize_text(value):
    value = str(value)

    # Repair words divided by PDF line-break hyphenation
    value = re.sub(r"(\w)-\s+(\w)", r"\1\2", value)

    # Normalize spaces and capitalization
    value = re.sub(r"\s+", " ", value)

    return value.casefold().strip()


# Prepare normalized text for each chunk
text_units_check = text_units.copy()

text_units_check["normalized_text"] = (
    text_units_check["text"].fillna("").map(normalize_text)
)


def inspect_text_unit_capture(fact_id):
    terms = fact_search_terms[fact_id]
    normalized_terms = [normalize_text(term) for term in terms]

    full_matches = []
    partial_matches = []

    for row_number, row in text_units_check.iterrows():
        chunk_text = row["normalized_text"]

        matched_terms = [
            original_term
            for original_term, normalized_term
            in zip(terms, normalized_terms)
            if normalized_term in chunk_text
        ]

        if len(matched_terms) == len(terms):
            full_matches.append(row_number + 1)

        elif matched_terms:
            partial_matches.append(
                {
                    "chunk": row_number + 1,
                    "matched_terms": matched_terms,
                }
            )

    if full_matches:
        capture = "YES"
        evidence_chunks = ", ".join(
            f"Chunk {number}" for number in full_matches
        )

    elif partial_matches:
        capture = "PARTIAL"
        evidence_chunks = "; ".join(
            f"Chunk {item['chunk']}: {', '.join(item['matched_terms'])}"
            for item in partial_matches
        )

    else:
        capture = "NO"
        evidence_chunks = ""

    return pd.Series(
        {
            "text_unit_capture": capture,
            "text_unit_evidence": evidence_chunks,
        }
    )


text_unit_results = recall_checklist["fact_id"].apply(
    inspect_text_unit_capture
)

recall_checklist["text_unit_capture"] = (
    text_unit_results["text_unit_capture"]
)

recall_checklist["text_unit_evidence"] = (
    text_unit_results["text_unit_evidence"]
)

print("Text-unit capture results:")
print(recall_checklist["text_unit_capture"].value_counts())

recall_checklist[
    [
        "fact_id",
        "category",
        "text_unit_capture",
        "text_unit_evidence",
        "source_fact",
    ]
]

Text-unit capture results:
text_unit_capture
YES        29
PARTIAL     1
Name: count, dtype: int64

,fact_id,category,text_unit_capture,text_unit_evidence,source_fact
0,P01,POLICY,PARTIAL,"Chunk 1: 100 Prozent, 2030; Chunk 2: 2030, ern...",The Renewable Expansion Act establishes that t...
1,P02,POLICY,YES,"Chunk 2, Chunk 5",The Renewable Expansion Act provides for at le...
2,P03,POLICY,YES,Chunk 2,RED III raises the EU renewable-energy share t...
3,P04,POLICY,YES,"Chunk 2, Chunk 10",Austria introduced a zero-percent VAT measure ...
4,P05,POLICY,YES,Chunk 7,The proposed Electricity Industry Act includes...
5,P06,POLICY,YES,Chunk 7,The planned Renewable Expansion Acceleration A...
6,P07,POLICY,YES,Chunk 7,"Building law, spatial planning and nature cons..."
7,P08,POLICY,YES,Chunk 7,The Federal-State Dialogue on Renewable Energy...
8,P09,POLICY,YES,"Chunk 6, Chunk 7",The 2022 amendment to the Condominium Act made...
9,P10,POLICY,YES,Chunk 3,The Austrian Photovoltaic Strategy is intended...
10,M01,MARKET_NUMERICAL,YES,"Chunk 2, Chunk 3",Austria reached 6.3 TWh of PV generation in 2023.
11,M02,MARKET_NUMERICAL,YES,"Chunk 1, Chunk 5",Approximately 2.5 GW of new photovoltaic capac...
12,M03,MARKET_NUMERICAL,YES,Chunk 5,One GW of new photovoltaic capacity was instal...
13,M04,MARKET_NUMERICAL,YES,"Chunk 1, Chunk 5, Chunk 10",The Integrated Austrian Network Infrastructure...
14,M05,MARKET_NUMERICAL,YES,Chunk 5,At least approximately 15 TWh of the 2040 PV p...
15,M06,MARKET_NUMERICAL,YES,"Chunk 5, Chunk 10",An average expansion rate of approximately 2 G...
16,M07,MARKET_NUMERICAL,YES,Chunk 5,The Transition 2040 scenario requires 21 TWh o...
17,M08,MARKET_NUMERICAL,YES,Chunk 5,The 21 TWh requirement for 2030 represents an ...
18,M09,MARKET_NUMERICAL,YES,Chunk 2,Approximately EUR 600 million was provided for...
19,M10,MARKET_NUMERICAL,YES,Chunk 5,"At the end of 2023, PV supplied almost 10% of ..."
20,T01,TECHNICAL,YES,Chunk 9,Digitalization of the distribution grid is imp...
21,T02,TECHNICAL,YES,Chunk 9,Photovoltaic generation peaks can no longer al...
22,T03,TECHNICAL,YES,Chunk 9,Smart local energy management and storage can ...
23,T04,TECHNICAL,YES,Chunk 9,PV should operate synergistically with electri...
24,T05,TECHNICAL,YES,Chunk 10,East-west-oriented and vertical PV installatio...
25,T06,TECHNICAL,YES,"Chunk 7, Chunk 8",Agri-PV enables combined agricultural and phot...
26,T07,TECHNICAL,YES,"Chunk 7, Chunk 11",Open-space PV installations should be designed...
27,T08,TECHNICAL,YES,Chunk 11,PV systems should be installed on federal buil...
28,T09,TECHNICAL,YES,Chunk 15,Energy communities should be further developed...
29,T10,TECHNICAL,YES,Chunk 14,PV research should address resource efficiency...

In [4]:
# Correct the alternative percentage spelling used in the document
fact_search_terms["P01"] = [
    "100 %",
    "2030",
    "erneuerbaren Energiequellen",
]

# Recalculate the text-unit results
text_unit_results = recall_checklist["fact_id"].apply(
    inspect_text_unit_capture
)

recall_checklist["text_unit_capture"] = (
    text_unit_results["text_unit_capture"]
)

recall_checklist["text_unit_evidence"] = (
    text_unit_results["text_unit_evidence"]
)

print("Corrected text-unit capture results:")
print(recall_checklist["text_unit_capture"].value_counts())

recall_checklist[
    recall_checklist["text_unit_capture"] != "YES"
][
    [
        "fact_id",
        "source_fact",
        "text_unit_capture",
        "text_unit_evidence",
    ]
]

Corrected text-unit capture results:
text_unit_capture
YES    30
Name: count, dtype: int64

Empty DataFrame
Columns: [fact_id, source_fact, text_unit_capture, text_unit_evidence]
Index: []

In [5]:
# Search terms for entity candidates related to the 10 policy facts
policy_entity_terms = {
    "P01": [
        "ERNEUERBAREN-AUSBAU-GESETZ",
        "ERNEUERBARE ENERGIE",
        "2030",
    ],
    "P02": [
        "ERNEUERBAREN-AUSBAU-GESETZ",
        "PHOTOVOLTAIK",
        "11 TWH",
    ],
    "P03": [
        "RED III",
        "EU-ERNEUERBAREN-RICHTLINIE",
        "42,5",
    ],
    "P04": [
        "UMSATZSTEUER",
        "35 KWP",
        "PV-ANLAGE",
    ],
    "P05": [
        "ELEKTRIZITÄTSWIRTSCHAFTSGESETZ",
        "ELWG",
        "NETZKAPAZITÄT",
        "NETZANSCHLUSS",
    ],
    "P06": [
        "ERNEUERBAREN-AUSBAU-BESCHLEUNIGUNGSGESETZ",
        "E-ABG",
        "EABG",
    ],
    "P07": [
        "BUNDESLÄNDER",
        "RAUMORDNUNG",
        "NATURSCHUTZ",
        "BAURECHT",
    ],
    "P08": [
        "BUND-LÄNDER-DIALOG",
        "BUND",
        "BUNDESLÄNDER",
    ],
    "P09": [
        "WOHNUNGSEIGENTUMSGESETZ",
        "WEG-NOVELLE",
        "REIHENHÄUSER",
    ],
    "P10": [
        "ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE",
        "PHOTOVOLTAIK-STRATEGIE",
        "LEBENDIGES DOKUMENT",
    ],
}


def find_entity_candidates(fact_id, search_terms, maximum=8):
    scored_candidates = []

    for _, entity in entities.iterrows():
        title = str(entity.get("title", ""))
        description = str(entity.get("description", ""))

        normalized_title = normalize_text(title)
        normalized_description = normalize_text(description)

        matched_terms = []

        for term in search_terms:
            normalized_term = normalize_text(term)

            if (
                normalized_term in normalized_title
                or normalized_term in normalized_description
            ):
                matched_terms.append(term)

        if matched_terms:
            scored_candidates.append(
                {
                    "fact_id": fact_id,
                    "entity_title": title,
                    "entity_type": entity.get("type", ""),
                    "matched_terms": "; ".join(matched_terms),
                    "number_of_matches": len(matched_terms),
                    "frequency": entity.get("frequency", ""),
                    "degree": entity.get("degree", ""),
                }
            )

    if not scored_candidates:
        return pd.DataFrame(
            [
                {
                    "fact_id": fact_id,
                    "entity_title": "NO CANDIDATE FOUND",
                    "entity_type": "",
                    "matched_terms": "",
                    "number_of_matches": 0,
                    "frequency": "",
                    "degree": "",
                }
            ]
        )

    result = pd.DataFrame(scored_candidates)

    return (
        result
        .sort_values(
            by=["number_of_matches", "degree", "frequency"],
            ascending=False,
        )
        .head(maximum)
    )


policy_candidate_tables = []

for fact_id, terms in policy_entity_terms.items():
    candidates = find_entity_candidates(
        fact_id=fact_id,
        search_terms=terms,
        maximum=8,
    )

    policy_candidate_tables.append(candidates)

policy_entity_candidates = pd.concat(
    policy_candidate_tables,
    ignore_index=True,
)

policy_entity_candidates[
    [
        "fact_id",
        "entity_title",
        "entity_type",
        "matched_terms",
        "frequency",
        "degree",
    ]
]

,fact_id,entity_title,entity_type,matched_terms,frequency,degree
0,P01,ERNEUERBAREN-AUSBAU-GESETZ (EAG),EVENT,ERNEUERBAREN-AUSBAU-GESETZ; 2030,2,5
1,P01,ÖSTERREICH,GEO,2030,15,82
2,P01,ENERGIEWENDE,EVENT,2030,7,6
3,P01,EPOOL,ORGANIZATION,ERNEUERBARE ENERGIE,3,5
4,P01,"HACKNER, JOHANNES",PERSON,ERNEUERBARE ENERGIE,2,5
5,P01,ERNEUERBAREN-AUSBAU-GESETZ,ORGANIZATION,ERNEUERBAREN-AUSBAU-GESETZ,1,5
6,P01,FIT FÜR 55,EVENT,2030,2,4
7,P01,ERNEUERBARE ENERGIEN,ORGANIZATION,ERNEUERBARE ENERGIE,1,4
8,P02,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,EVENT,PHOTOVOLTAIK,14,39
9,P02,PHOTOVOLTAIKANLAGEN,ORGANIZATION,PHOTOVOLTAIK,2,13
10,P02,PHOTOVOLTAIK-STRATEGIE,EVENT,PHOTOVOLTAIK,1,6
11,P02,ERNEUERBAREN-AUSBAU-GESETZ (EAG),EVENT,ERNEUERBAREN-AUSBAU-GESETZ,2,5
12,P02,PHOTOVOLTAIK,EVENT,PHOTOVOLTAIK,2,5
13,P02,ERNEUERBAREN-AUSBAU-GESETZ,ORGANIZATION,ERNEUERBAREN-AUSBAU-GESETZ,1,5
14,P02,PHOTOVOLTAIK (PV),EVENT,PHOTOVOLTAIK,1,4
15,P02,PHOTOVOLTAIK-PROJEKTE,EVENT,PHOTOVOLTAIK,1,4
16,P03,EU-ERNEUERBAREN-RICHTLINIE (RED III),ORGANIZATION,RED III; EU-ERNEUERBAREN-RICHTLINIE,1,2
17,P03,RED III,EVENT,RED III,2,5
18,P03,EUROPÄISCHE UNION,ORGANIZATION,RED III,2,4
19,P03,ERNNEUERBAREN-BESCHLEUNIGUNGSGEBIETE (RENEWABL...,GEO,RED III,1,2
20,P04,UMSATZSTEUER-BEFRREIUNG 2024/2025,EVENT,UMSATZSTEUER; 35 KWP,1,2
21,P04,PV-ANLAGE,ORGANIZATION,PV-ANLAGE,3,20
22,P04,PV-ANLAGEN,EVENT,PV-ANLAGE,2,7
23,P04,AGRI-PV-ANLAGEN,ORGANIZATION,PV-ANLAGE,4,5
24,P04,PV-ANLAGENBETREIBER:INNEN,PERSON,PV-ANLAGE,1,2
25,P04,HANDLUNGSANLEITUNG FÜR DIE ERRICHTUNG VON PV-A...,EVENT,PV-ANLAGE,1,2
26,P04,ELEKTROTECHNISCHE NORMUNGSORGANISATION,ORGANIZATION,PV-ANLAGE,1,1
27,P04,BETREIBER:INNEN DER PV-ANLAGEN,PERSON,PV-ANLAGE,1,1
28,P05,ELEKTRIZITÄTSWIRTSCHAFTSGESETZ (ELWG),EVENT,ELEKTRIZITÄTSWIRTSCHAFTSGESETZ; ELWG,3,5
29,P05,ELWG – ELEKTRIZITÄTSWIRTSCHAFTSGESETZ,EVENT,ELEKTRIZITÄTSWIRTSCHAFTSGESETZ; ELWG,1,3
30,P05,E-CONTROL,ORGANIZATION,NETZANSCHLUSS,6,11
31,P05,AKTIONSPLAN NETZANSCHLUSS 2023,EVENT,NETZANSCHLUSS,2,2
32,P05,AKTIONSPLAN NETZANSCHLUSS,EVENT,NETZANSCHLUSS,1,2
33,P05,13 AKTIONSPLAN NETZANSCHLUSS,EVENT,NETZANSCHLUSS,1,2
34,P05,ELEKTRIZITÄTSWIRTSCHAFTSGESETZ,EVENT,ELEKTRIZITÄTSWIRTSCHAFTSGESETZ,1,1
35,P05,ELWOG – ELEKTRIZITÄTSWIRTSCHAFTS- UND -ORGANIS...,EVENT,ELWG,1,1
36,P06,ERNEUERBAREN-AUSBAU-BESCHLEUNIGUNGSGESETZ (E-ABG),EVENT,ERNEUERBAREN-AUSBAU-BESCHLEUNIGUNGSGESETZ; E-ABG,1,2
37,P06,ERNEUERBAREN-AUSBAU-BESCHLEUNIGUNGSGESETZ (EABG),EVENT,ERNEUERBAREN-AUSBAU-BESCHLEUNIGUNGSGESETZ; EABG,1,0
38,P06,EABG,ORGANIZATION,EABG,1,1
39,P07,BUND,ORGANIZATION,BUNDESLÄNDER,1,14
40,P07,BUNDESLÄNDER,GEO,BUNDESLÄNDER,4,11
41,P07,BUND-LÄNDER-DIALOG ERNEUERBARE ENERGIE,ORGANIZATION,BUNDESLÄNDER,1,3
42,P07,ENERGIEBERATUNGSSTELLEN DER BUNDESLÄNDER,ORGANIZATION,BUNDESLÄNDER,1,2
43,P08,BUND-LÄNDER-DIALOG ERNEUERBARE ENERGIE,ORGANIZATION,BUND-LÄNDER-DIALOG; BUND; BUNDESLÄNDER,1,3
44,P08,BUND,ORGANIZATION,BUND; BUNDESLÄNDER,1,14
45,P08,BUNDESLÄNDER,GEO,BUND; BUNDESLÄNDER,4,11
46,P08,ENERGIEBERATUNGSSTELLEN DER BUNDESLÄNDER,ORGANIZATION,BUND; BUNDESLÄNDER,1,2
47,P08,LANDESENERGIEREFERENT:INNEN,PERSON,BUND-LÄNDER-DIALOG; BUND,1,1
48,P08,BMK,ORGANIZATION,BUND,7,16
49,P08,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",ORGANIZATION,BUND,2,9
50,P08,BUNDESVERBAND PV AUSTRIA,ORGANIZATION,BUND,1,7
51,P09,"BUNDESGESETZ, MIT DEM DAS WOHNUNGSEIGENTUMSGES...",EVENT,WOHNUNGSEIGENTUMSGESETZ; WEG-NOVELLE,1,1
52,P09,WOHNUNGSEIGENTUMSGESETZ,EVENT,WOHNUNGSEIGENTUMSGESETZ,2,5
53,P09,REIHENHÄUSER,GEO,REIHENHÄUSER,1,1
54,P10,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,EVENT,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE; PHOTOV...,14,39
55,P10,PHOTOVOLTAIK-STRATEGIE,EVENT,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE; PHOTOV...,1,6
56,P10,CAJETAN PERWEIN,PERSON,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE; PHOTOV...,1,1

In [6]:
def set_entity_capture(fact_id, capture, notes):
    mask = recall_checklist["fact_id"] == fact_id

    recall_checklist.loc[
        mask,
        "entity_capture"
    ] = capture

    recall_checklist.loc[
        mask,
        "audit_notes"
    ] = notes


set_entity_capture(
    "P01",
    "PARTIAL",
    (
        "Austria and the Renewable Expansion Act were extracted, but the "
        "100% renewable-electricity target for 2030 was not represented as "
        "a dedicated structured target entity. The Act was typed as EVENT "
        "or ORGANIZATION."
    ),
)

set_entity_capture(
    "P02",
    "PARTIAL",
    (
        "The Renewable Expansion Act and Photovoltaics were extracted, but "
        "the 11 TWh target and its 2030 date were not represented as dedicated "
        "target/value entities. Several aliases and inconsistent types exist."
    ),
)

set_entity_capture(
    "P03",
    "PARTIAL",
    (
        "RED III and the European Union were extracted, but the 42.5% target, "
        "45% ambition and 2030 deadline were not represented as structured "
        "target entities. RED III also appears under different raw types."
    ),
)

set_entity_capture(
    "P04",
    "PARTIAL",
    (
        "The VAT exemption and PV installations were extracted, but the "
        "35 kWp eligibility threshold was not represented as a dedicated "
        "structured entity or attribute. The support scheme was typed as EVENT."
    ),
)

set_entity_capture(
    "P05",
    "PARTIAL",
    (
        "The Electricity Industry Act, E-Control and grid-connection action "
        "plans were extracted. However, simplified grid connection and grid "
        "capacity transparency were not represented as clear controlled "
        "entities. Multiple aliases of the Act were produced."
    ),
)

set_entity_capture(
    "P06",
    "FULL",
    (
        "The Renewable Expansion Acceleration Act, PV installations and "
        "infrastructure concepts were extracted. The essential concepts are "
        "present, although the Act is incorrectly typed as EVENT and duplicate "
        "E-ABG/EABG forms exist."
    ),
)

set_entity_capture(
    "P07",
    "PARTIAL",
    (
        "The federal states were extracted, but building law, spatial planning "
        "and nature-conservation responsibilities were not consistently "
        "represented as separate controlled concepts. Bundesländer was typed "
        "as GEO."
    ),
)

set_entity_capture(
    "P08",
    "FULL",
    (
        "The Federal-State Dialogue, Federal Government and Federal States "
        "were extracted. The core actors are present, although the dialogue "
        "was typed as ORGANIZATION and broad entities such as BUND remain "
        "overgeneralized."
    ),
)

set_entity_capture(
    "P09",
    "FULL",
    (
        "The Condominium Act amendment, PV systems and relevant building "
        "concepts were extracted. The main source concepts are present, but "
        "the law was typed as EVENT rather than POLICY or LAW."
    ),
)

set_entity_capture(
    "P10",
    "PARTIAL",
    (
        "The Austrian Photovoltaic Strategy was extracted, including shortened "
        "duplicate names. However, its status as a living document that should "
        "change with future developments was not represented as a separate "
        "process or property."
    ),
)

recall_checklist[
    recall_checklist["fact_id"].str.startswith("P")
][
    [
        "fact_id",
        "source_fact",
        "entity_capture",
        "audit_notes",
    ]
]

,fact_id,source_fact,entity_capture,audit_notes
0,P01,The Renewable Expansion Act establishes that t...,PARTIAL,Austria and the Renewable Expansion Act were e...
1,P02,The Renewable Expansion Act provides for at le...,PARTIAL,The Renewable Expansion Act and Photovoltaics ...
2,P03,RED III raises the EU renewable-energy share t...,PARTIAL,"RED III and the European Union were extracted,..."
3,P04,Austria introduced a zero-percent VAT measure ...,PARTIAL,The VAT exemption and PV installations were ex...
4,P05,The proposed Electricity Industry Act includes...,PARTIAL,"The Electricity Industry Act, E-Control and gr..."
5,P06,The planned Renewable Expansion Acceleration A...,FULL,"The Renewable Expansion Acceleration Act, PV i..."
6,P07,"Building law, spatial planning and nature cons...",PARTIAL,"The federal states were extracted, but buildin..."
7,P08,The Federal-State Dialogue on Renewable Energy...,FULL,"The Federal-State Dialogue, Federal Government..."
8,P09,The 2022 amendment to the Condominium Act made...,FULL,"The Condominium Act amendment, PV systems and ..."
9,P10,The Austrian Photovoltaic Strategy is intended...,PARTIAL,The Austrian Photovoltaic Strategy was extract...

In [7]:
market_entity_terms = {
    "M01": [
        "6,3 TWH",
        "PV-ERZEUGUNG",
        "PHOTOVOLTAIK",
        "2023",
    ],
    "M02": [
        "2,5 GW",
        "PV-AUSBAU",
        "NEUINSTALLATION",
        "2023",
    ],
    "M03": [
        "1 GW",
        "GIGAWATT",
        "NEUINSTALLATION",
        "2022",
    ],
    "M04": [
        "41 TWH",
        "NETZINFRASTRUKTURPLAN",
        "PHOTOVOLTAIK",
        "2040",
    ],
    "M05": [
        "15 TWH",
        "GEBÄUDE",
        "PV-POTENTIAL",
        "2040",
    ],
    "M06": [
        "2 GW PRO JAHR",
        "PV-AUSBAU",
        "2040",
    ],
    "M07": [
        "21 TWH",
        "TRANSITION 2040",
        "PHOTOVOLTAIK",
        "2030",
    ],
    "M08": [
        "19 TWH",
        "PV-AUSBAU",
        "2020",
        "2030",
    ],
    "M09": [
        "600 MIO. EURO",
        "KLIMA- UND ENERGIEFONDS",
        "ERNEUERBAREN-AUSBAU-GESETZ",
        "2023",
    ],
    "M10": [
        "10 %",
        "2 %",
        "STROMENDVERBRAUCH",
        "ENERGIEBEDARF",
        "2023",
    ],
}


market_candidate_tables = []

for fact_id, terms in market_entity_terms.items():
    candidates = find_entity_candidates(
        fact_id=fact_id,
        search_terms=terms,
        maximum=8,
    )

    market_candidate_tables.append(candidates)

market_entity_candidates = pd.concat(
    market_candidate_tables,
    ignore_index=True,
)

market_entity_candidates[
    [
        "fact_id",
        "entity_title",
        "entity_type",
        "matched_terms",
        "frequency",
        "degree",
    ]
]

,fact_id,entity_title,entity_type,matched_terms,frequency,degree
0,M01,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,EVENT,PHOTOVOLTAIK,14,39
1,M01,KLIMA- UND ENERGIEFONDS,ORGANIZATION,2023,6,14
2,M01,PHOTOVOLTAIKANLAGEN,ORGANIZATION,PHOTOVOLTAIK,2,13
3,M01,E-CONTROL,ORGANIZATION,2023,6,11
4,M01,PHOTOVOLTAIK-STRATEGIE,EVENT,PHOTOVOLTAIK,1,6
...,...,...,...,...,...,...
75,M10,AKTIONSPLAN NETZANSCHLUSS 2023,EVENT,2023,2,2
76,M10,EU-ERNEUERBAREN-RICHTLINIE (RED III),ORGANIZATION,2023,1,2
77,M10,13 AKTIONSPLAN NETZANSCHLUSS,EVENT,2023,1,2
78,M10,P. BIERMAYR,PERSON,2023,2,1
79,M10,NATURE RESTORATION LAW,EVENT,2023,1,1

In [8]:
market_entity_assessments = {
    "M01": (
        "PARTIAL",
        (
            "Photovoltaics and Austria were extracted, but 6.3 TWh of PV "
            "generation in 2023 was not represented as a dedicated structured "
            "market-metric entity."
        ),
    ),
    "M02": (
        "PARTIAL",
        (
            "PV expansion and Austria were represented generally, but the "
            "2.5 GW addition in 2023 was not represented as a structured "
            "metric with value, unit and year."
        ),
    ),
    "M03": (
        "PARTIAL",
        (
            "Photovoltaic expansion was represented generally, but the "
            "1 GW addition in 2022 was not represented as a dedicated "
            "market-metric entity."
        ),
    ),
    "M04": (
        "PARTIAL",
        (
            "The Network Infrastructure Plan and Photovoltaics were extracted, "
            "but the 41 TWh by 2040 target was not represented as a dedicated "
            "target containing value, unit and deadline."
        ),
    ),
    "M05": (
        "PARTIAL",
        (
            "Buildings and PV-related concepts were extracted, but the "
            "15 TWh building potential was not represented as a structured "
            "metric or target."
        ),
    ),
    "M06": (
        "PARTIAL",
        (
            "PV expansion and the 2040 context appear in generated descriptions, "
            "but the required average rate of approximately 2 GW per year was "
            "not represented as a dedicated metric."
        ),
    ),
    "M07": (
        "PARTIAL",
        (
            "Transition 2040 and Photovoltaics were represented, but the "
            "21 TWh requirement for 2030 was not represented as a structured "
            "target."
        ),
    ),
    "M08": (
        "PARTIAL",
        (
            "PV expansion and the relevant years occur in generated output, "
            "but the 19 TWh increase between 2020 and 2030 was not represented "
            "as a structured market metric."
        ),
    ),
    "M09": (
        "PARTIAL",
        (
            "The Renewable Expansion Act and Climate and Energy Fund were "
            "extracted, but the approximately EUR 600 million provided in "
            "2023 was not represented as a dedicated funding-value entity."
        ),
    ),
    "M10": (
        "PARTIAL",
        (
            "Photovoltaics and Austrian energy concepts were extracted, but "
            "the approximately 10% electricity share and 2% total-energy share "
            "in 2023 were not represented as structured indicators."
        ),
    ),
}


for fact_id, (capture, notes) in market_entity_assessments.items():
    set_entity_capture(
        fact_id=fact_id,
        capture=capture,
        notes=notes,
    )


recall_checklist[
    recall_checklist["fact_id"].str.startswith("M")
][
    [
        "fact_id",
        "source_fact",
        "entity_capture",
        "audit_notes",
    ]
]

,fact_id,source_fact,entity_capture,audit_notes
10,M01,Austria reached 6.3 TWh of PV generation in 2023.,PARTIAL,"Photovoltaics and Austria were extracted, but ..."
11,M02,Approximately 2.5 GW of new photovoltaic capac...,PARTIAL,PV expansion and Austria were represented gene...
12,M03,One GW of new photovoltaic capacity was instal...,PARTIAL,Photovoltaic expansion was represented general...
13,M04,The Integrated Austrian Network Infrastructure...,PARTIAL,The Network Infrastructure Plan and Photovolta...
14,M05,At least approximately 15 TWh of the 2040 PV p...,PARTIAL,Buildings and PV-related concepts were extract...
15,M06,An average expansion rate of approximately 2 G...,PARTIAL,PV expansion and the 2040 context appear in ge...
16,M07,The Transition 2040 scenario requires 21 TWh o...,PARTIAL,Transition 2040 and Photovoltaics were represe...
17,M08,The 21 TWh requirement for 2030 represents an ...,PARTIAL,PV expansion and the relevant years occur in g...
18,M09,Approximately EUR 600 million was provided for...,PARTIAL,The Renewable Expansion Act and Climate and En...
19,M10,"At the end of 2023, PV supplied almost 10% of ...",PARTIAL,Photovoltaics and Austrian energy concepts wer...

In [9]:
technical_entity_assessments = {
    "T01": (
        "PARTIAL",
        (
            "The distribution grid was extracted, but digitalization specifically "
            "as a technical enabler of decentralized renewable integration was not "
            "represented as a complete controlled entity structure."
        ),
    ),
    "T02": (
        "PARTIAL",
        (
            "The electricity grid and Photovoltaics were extracted, but PV "
            "generation peaks and the grid's inability to absorb them completely "
            "were not represented as dedicated entities."
        ),
    ),
    "T03": (
        "PARTIAL",
        (
            "Smart local energy management and storage-related concepts were "
            "extracted, but self-consumption and generation/consumption peak "
            "management were not fully represented as separate concepts."
        ),
    ),
    "T04": (
        "FULL",
        (
            "Photovoltaics, e-mobility, heat pumps, hydrogen and storage-related "
            "technologies were extracted. The essential technical concepts are "
            "present, although several received unsuitable generic GraphRAG types."
        ),
    ),
    "T05": (
        "MISSING",
        (
            "General PV concepts were extracted, but neither east-west-oriented "
            "PV nor vertical PV was represented as a dedicated entity. The "
            "specific technical approach for shoulder and winter generation "
            "was therefore missed at the entity level."
        ),
    ),
    "T06": (
        "PARTIAL",
        (
            "Agri-PV installations were extracted, but agricultural dual use and "
            "land-use efficiency were not represented as complete controlled "
            "concepts. Agri-PV was also typed as ORGANIZATION."
        ),
    ),
    "T07": (
        "PARTIAL",
        (
            "Open-space PV and several biodiversity-PV concepts were extracted, "
            "but the requirement to follow defined ecological criteria was not "
            "represented as a separate controlled concept."
        ),
    ),
    "T08": (
        "PARTIAL",
        (
            "Federal buildings and PV systems were extracted, but the technical "
            "and economic feasibility conditions were not represented as "
            "structured constraints."
        ),
    ),
    "T09": (
        "PARTIAL",
        (
            "Energy communities, storage and flexibility concepts were extracted, "
            "but real-time operational monitoring and the complete implementation "
            "combination were not represented as structured entities."
        ),
    ),
    "T10": (
        "PARTIAL",
        (
            "PV circular economy and repair were extracted, but resource "
            "efficiency, durability, reuse and recycling were not all represented "
            "as separate controlled concepts."
        ),
    ),
}


for fact_id, (capture, notes) in technical_entity_assessments.items():
    set_entity_capture(
        fact_id=fact_id,
        capture=capture,
        notes=notes,
    )


print("Technical entity coverage:")
print(
    recall_checklist[
        recall_checklist["fact_id"].str.startswith("T")
    ]["entity_capture"].value_counts()
)

recall_checklist[
    recall_checklist["fact_id"].str.startswith("T")
][
    [
        "fact_id",
        "source_fact",
        "entity_capture",
        "audit_notes",
    ]
]

Technical entity coverage:
entity_capture
PARTIAL    8
FULL       1
MISSING    1
Name: count, dtype: int64

,fact_id,source_fact,entity_capture,audit_notes
20,T01,Digitalization of the distribution grid is imp...,PARTIAL,"The distribution grid was extracted, but digit..."
21,T02,Photovoltaic generation peaks can no longer al...,PARTIAL,The electricity grid and Photovoltaics were ex...
22,T03,Smart local energy management and storage can ...,PARTIAL,Smart local energy management and storage-rela...
23,T04,PV should operate synergistically with electri...,FULL,"Photovoltaics, e-mobility, heat pumps, hydroge..."
24,T05,East-west-oriented and vertical PV installatio...,MISSING,"General PV concepts were extracted, but neithe..."
25,T06,Agri-PV enables combined agricultural and phot...,PARTIAL,"Agri-PV installations were extracted, but agri..."
26,T07,Open-space PV installations should be designed...,PARTIAL,Open-space PV and several biodiversity-PV conc...
27,T08,PV systems should be installed on federal buil...,PARTIAL,Federal buildings and PV systems were extracte...
28,T09,Energy communities should be further developed...,PARTIAL,"Energy communities, storage and flexibility co..."
29,T10,PV research should address resource efficiency...,PARTIAL,"PV circular economy and repair were extracted,..."

In [10]:
print("Overall entity coverage:")
print(recall_checklist["entity_capture"].value_counts())

print()
print("Entity coverage by category:")
print(
    pd.crosstab(
        recall_checklist["category"],
        recall_checklist["entity_capture"],
    )
)

Overall entity coverage:
entity_capture
PARTIAL    25
FULL        4
MISSING     1
Name: count, dtype: int64

Entity coverage by category:
entity_capture    FULL  MISSING  PARTIAL
category
MARKET_NUMERICAL     0        0       10
POLICY               3        0        7
TECHNICAL            1        1        8

In [11]:
policy_relationship_terms = {
    "P01": [
        "ERNEUERBAREN-AUSBAU-GESETZ",
        "ÖSTERREICH",
        "2030",
        "100",
    ],
    "P02": [
        "ERNEUERBAREN-AUSBAU-GESETZ",
        "PHOTOVOLTAIK",
        "11 TWH",
        "2030",
    ],
    "P03": [
        "RED III",
        "EUROPÄISCHE UNION",
        "42,5",
        "2030",
    ],
    "P04": [
        "UMSATZSTEUER",
        "PV-ANLAGE",
        "35 KWP",
    ],
    "P05": [
        "ELEKTRIZITÄTSWIRTSCHAFTSGESETZ",
        "NETZANSCHLUSS",
        "NETZKAPAZITÄT",
    ],
    "P06": [
        "ERNEUERBAREN-AUSBAU-BESCHLEUNIGUNGSGESETZ",
        "PV-ANLAGE",
        "VERFAHREN",
    ],
    "P07": [
        "BUNDESLÄNDER",
        "RAUMORDNUNG",
        "NATURSCHUTZ",
    ],
    "P08": [
        "BUND-LÄNDER-DIALOG",
        "BUND",
        "BUNDESLÄNDER",
    ],
    "P09": [
        "WOHNUNGSEIGENTUMSGESETZ",
        "PV-ANLAGE",
        "GEBÄUDE",
    ],
    "P10": [
        "PHOTOVOLTAIK-STRATEGIE",
        "LEBENDIGES DOKUMENT",
        "ANPASS",
    ],
}


def find_relationship_candidates(
    fact_id,
    search_terms,
    maximum=3,
):
    scored_candidates = []

    for _, relationship in relationships.iterrows():
        source = str(relationship.get("source", ""))
        target = str(relationship.get("target", ""))
        description = str(relationship.get("description", ""))

        combined_text = normalize_text(
            source + " " + target + " " + description
        )

        matched_terms = []

        for term in search_terms:
            normalized_term = normalize_text(term)

            if normalized_term in combined_text:
                matched_terms.append(term)

        if matched_terms:
            scored_candidates.append(
                {
                    "fact_id": fact_id,
                    "source": source,
                    "target": target,
                    "description": description,
                    "matched_terms": "; ".join(matched_terms),
                    "number_of_matches": len(matched_terms),
                    "weight": relationship.get("weight", ""),
                }
            )

    if not scored_candidates:
        return pd.DataFrame(
            [
                {
                    "fact_id": fact_id,
                    "source": "NO CANDIDATE FOUND",
                    "target": "",
                    "description": "",
                    "matched_terms": "",
                    "number_of_matches": 0,
                    "weight": "",
                }
            ]
        )

    result = pd.DataFrame(scored_candidates)

    return (
        result
        .sort_values(
            by=["number_of_matches", "weight"],
            ascending=False,
        )
        .head(maximum)
    )


policy_relationship_tables = []

for fact_id, terms in policy_relationship_terms.items():
    candidates = find_relationship_candidates(
        fact_id=fact_id,
        search_terms=terms,
        maximum=3,
    )

    policy_relationship_tables.append(candidates)

policy_relationship_candidates = pd.concat(
    policy_relationship_tables,
    ignore_index=True,
)

pd.set_option("display.max_colwidth", 100)

policy_relationship_candidates[
    [
        "fact_id",
        "source",
        "target",
        "matched_terms",
        "description",
    ]
]

,fact_id,source,target,matched_terms,description
0,P01,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖSTERREICH,ERNEUERBAREN-AUSBAU-GESETZ; ÖSTERREICH,The EAG is an Austrian law that sets a legal and financial framework to support the country's re...
1,P01,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ERNEUERBAREN-AUSBAU-GESETZ; ÖSTERREICH,The EAG is a backbone legal act referenced and operationalized by the National Photovoltaic Stra...
2,P01,ERNEUERBAREN-AUSBAU-GESETZ,ÖSTERREICH,ERNEUERBAREN-AUSBAU-GESETZ; ÖSTERREICH,The Renewable Energy Expansion Act is Austrian legislation designed to support energy transition...
3,P02,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ERNEUERBAREN-AUSBAU-GESETZ; PHOTOVOLTAIK,The EAG is a backbone legal act referenced and operationalized by the National Photovoltaic Stra...
4,P02,PHOTOVOLTAIK (PV),ERNEUERBAREN-AUSBAU-GESETZ (EAG),ERNEUERBAREN-AUSBAU-GESETZ; PHOTOVOLTAIK,The EAG legal framework prioritizes and enables the expansion of photovoltaics.
5,P02,ERNEUERBAREN-AUSBAU-GESETZ,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ERNEUERBAREN-AUSBAU-GESETZ; PHOTOVOLTAIK,The Renewable Energy Expansion Act provides the legal and financial framework for Austria's Phot...
6,P03,EUROPÄISCHE UNION,RED III,RED III; EUROPÄISCHE UNION,"RED III is an EU directive mandating member state action on renewable energy acceleration, impac..."
7,P03,EUROPÄISCHE UNION,ÖSTERREICH,EUROPÄISCHE UNION,Austria (ÖSTERREICH) is a member state of the European Union (EUROPÄISCHE UNION) and is therefor...
8,P03,EUROPÄISCHE KOMMISSION,FIT FÜR 55,2030,"The European Commission introduced the ""Fit für 55"" legislative package as a central component o..."
9,P04,UMSATZSTEUER-BEFRREIUNG 2024/2025,UMSATZSTEUER,UMSATZSTEUER; 35 KWP,The VAT exemption for PV (up to 35 kWp) is a fiscal event for 2024 and 2025 specifically targeti...
10,P04,BUNDESLÄNDER,PV-ANLAGE,PV-ANLAGE,"The BUNDESLÄNDER, which are the federal states in Austria, play a significant role in supporting..."
11,P04,AKTIVER KUNDE,PV-ANLAGE,PV-ANLAGE,AKTIVER KUNDE refers to active customers who are individual users or residents primarily utilizi...
12,P05,AKTIONSPLAN NETZANSCHLUSS 2023,13 AKTIONSPLAN NETZANSCHLUSS,NETZANSCHLUSS,The 2023 Grid Connection Action Plan is the specific 13th action plan described.
13,P05,E-CONTROL,AKTIONSPLAN NETZANSCHLUSS,NETZANSCHLUSS,E-Control is the creator or responsible body for the Aktionsplan Netzanschluss.
14,P05,ELEKTRIZITÄTSWIRTSCHAFTSGESETZ (ELWG),ÖSTERREICH,ELEKTRIZITÄTSWIRTSCHAFTSGESETZ,The ElWG is Austria's law governing the electricity industry.
15,P06,BUNDESLÄNDER,PV-ANLAGE,PV-ANLAGE,"The BUNDESLÄNDER, which are the federal states in Austria, play a significant role in supporting..."
16,P06,AKTIVER KUNDE,PV-ANLAGE,PV-ANLAGE,AKTIVER KUNDE refers to active customers who are individual users or residents primarily utilizi...
17,P06,PV-ANLAGE,AGRI-PV-ANLAGEN,PV-ANLAGE,"PV-ANLAGE refers to photovoltaic systems, commonly known as solar power installations, that are ..."
18,P07,ÖSTERREICH,BUNDESLÄNDER,BUNDESLÄNDER,"ÖSTERREICH, also known as Austria, is divided into regional entities called Bundesländer, or fed..."
19,P07,BUNDESLÄNDER,PV-ANLAGE,BUNDESLÄNDER,"The BUNDESLÄNDER, which are the federal states in Austria, play a significant role in supporting..."
20,P07,BUND,BUNDESLÄNDER,BUNDESLÄNDER,The Bund (federal government) and the Bundesländer (states) collaborate to reach national and re...
21,P08,BUND-LÄNDER-DIALOG ERNEUERBARE ENERGIE,BUNDESLÄNDER,BUND-LÄNDER-DIALOG; BUND; BUNDESLÄNDER,The committee works through active participation by both the federal government and all Austrian...
22,P08,ÖSTERREICH,BUNDESLÄNDER,BUND; BUNDESLÄNDER,"ÖSTERREICH, also known as Austria, is divided into regional entities called Bundesländer, or fed..."
23,P08,BUNDESLÄNDER,PV-ANLAGE,BUND; BUNDESLÄNDER,"The BUNDESLÄNDER, which are the federal states in Austria, play a significant role in supporting..."
24,P09,PV-ANLAGE,GEBÄUDEAUSSENTEILE,PV-ANLAGE; GEBÄUDE,"Building exteriors increasingly act as standard locations for PV installation, integrating energ..."
25,P09,EINZELGEBÄUDE,WOHNUNGSEIGENTUMSGESETZ,WOHNUNGSEIGENTUMSGESETZ; GEBÄUDE,Individual buildings are also beneficiaries of the new regulations for PV expansion.
26,P09,BUNDESLÄNDER,PV-ANLAGE,PV-ANLAGE,"The BUNDESLÄNDER, which are the federal states in Austria, play a significant role in supporting..."
27,P10,ÖSTERREICH,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,PHOTOVOLTAIK-STRATEGIE,ÖSTERREICH (Austria) is both the creator and primary beneficiary of the ÖSTERREICHISCHE PHOTOVOL...
28,P10,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ÖSTERREICH,PHOTOVOLTAIK-STRATEGIE,"The ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE, also known as the Austrian Photovoltaic Strategy, is..."
29,P10,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENERGIE, MOBILITÄT, INNOVATION UND TECHNOLOGIE",ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,PHOTOVOLTAIK-STRATEGIE,"The BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENERGIE, MOBILITÄT, INNOVATION UND TECHNOLOGIE (F..."

In [12]:
def set_relationship_capture(fact_id, capture, notes):
    mask = recall_checklist["fact_id"] == fact_id

    recall_checklist.loc[
        mask,
        "relationship_capture"
    ] = capture

    # Append relationship notes without removing entity notes
    existing_notes = recall_checklist.loc[
        mask,
        "audit_notes"
    ].fillna("")

    recall_checklist.loc[
        mask,
        "audit_notes"
    ] = (
        existing_notes
        + " Relationship assessment: "
        + notes
    )


policy_relationship_assessments = {
    "P01": (
        "MISSING",
        (
            "Relationships involving the Renewable Expansion Act and Austria "
            "exist, but none preserves the specific 100% renewable-electricity "
            "target for 2030."
        ),
    ),
    "P02": (
        "MISSING",
        (
            "The Renewable Expansion Act is connected to Photovoltaics and "
            "renewable-energy expansion, but the specific 11 TWh target for "
            "2030 is absent."
        ),
    ),
    "P03": (
        "MISSING",
        (
            "RED III is connected to the European Union and Austria, but the "
            "42.5% target, 45% ambition and 2030 deadline are absent from the "
            "relationship structure."
        ),
    ),
    "P04": (
        "PARTIAL",
        (
            "A relationship description mentions the VAT exemption for PV "
            "systems up to 35 kWp, but its endpoints connect the exemption to "
            "VAT rather than directly representing the support relationship "
            "between the exemption and eligible PV systems."
        ),
    ),
    "P05": (
        "PARTIAL",
        (
            "Relationships involving the Electricity Industry Act, Austria and "
            "EU legislation exist, but simplified grid connection and grid-"
            "capacity transparency are not represented completely."
        ),
    ),
    "P06": (
        "PARTIAL",
        (
            "The acceleration act is related to federal legislation and "
            "expedited renewable infrastructure deployment, but the specific "
            "permitting relationship for PV installations is incomplete."
        ),
    ),
    "P07": (
        "PARTIAL",
        (
            "Separate relationships connect nature conservation and spatial "
            "planning to the federal states. However, the complete responsibility "
            "covering building law, spatial planning and nature conservation is "
            "fragmented and building law is not clearly represented."
        ),
    ),
    "P08": (
        "PARTIAL",
        (
            "The Federal-State Dialogue is connected to the federal government "
            "and federal states, and policy harmonization is mentioned. Detailed "
            "coordination of targets, land, processes and support strategies is "
            "not fully preserved."
        ),
    ),
    "P09": (
        "FULL",
        (
            "Relationships explicitly connect the Condominium Act amendment "
            "with easier PV installation and terraced houses. The essential "
            "meaning of the source fact is preserved."
        ),
    ),
    "P10": (
        "MISSING",
        (
            "The Austrian Photovoltaic Strategy has several relationships, but "
            "none represents its status as a living document that should be "
            "updated when conditions change."
        ),
    ),
}


for fact_id, (capture, notes) in policy_relationship_assessments.items():
    set_relationship_capture(
        fact_id=fact_id,
        capture=capture,
        notes=notes,
    )


print("Policy relationship coverage:")
print(
    recall_checklist[
        recall_checklist["fact_id"].str.startswith("P")
    ]["relationship_capture"].value_counts()
)

recall_checklist[
    recall_checklist["fact_id"].str.startswith("P")
][
    [
        "fact_id",
        "source_fact",
        "relationship_capture",
        "audit_notes",
    ]
]

Policy relationship coverage:
relationship_capture
PARTIAL    5
MISSING    4
FULL       1
Name: count, dtype: int64

,fact_id,source_fact,relationship_capture,audit_notes
0,P01,The Renewable Expansion Act establishes that total electricity consumption should be covered nat...,MISSING,"Austria and the Renewable Expansion Act were extracted, but the 100% renewable-electricity targe..."
1,P02,The Renewable Expansion Act provides for at least 11 TWh of additional photovoltaic generation b...,MISSING,"The Renewable Expansion Act and Photovoltaics were extracted, but the 11 TWh target and its 2030..."
2,P03,"RED III raises the EU renewable-energy share target to 42.5%, with 45% to be aimed for, by 2030.",MISSING,"RED III and the European Union were extracted, but the 42.5% target, 45% ambition and 2030 deadl..."
3,P04,Austria introduced a zero-percent VAT measure for eligible PV systems with a capacity of up to 3...,PARTIAL,"The VAT exemption and PV installations were extracted, but the 35 kWp eligibility threshold was ..."
4,P05,The proposed Electricity Industry Act includes simplified grid connection for small systems and ...,PARTIAL,"The Electricity Industry Act, E-Control and grid-connection action plans were extracted. However..."
5,P06,The planned Renewable Expansion Acceleration Act is intended to accelerate procedures for PV ins...,PARTIAL,"The Renewable Expansion Acceleration Act, PV installations and infrastructure concepts were extr..."
6,P07,"Building law, spatial planning and nature conservation are primarily responsibilities of the Aus...",PARTIAL,"The federal states were extracted, but building law, spatial planning and nature-conservation re..."
7,P08,"The Federal-State Dialogue on Renewable Energy coordinates federal and state targets, land avail...",PARTIAL,"The Federal-State Dialogue, Federal Government and Federal States were extracted. The core actor..."
8,P09,The 2022 amendment to the Condominium Act made the construction of PV systems on terraced houses...,FULL,"The Condominium Act amendment, PV systems and relevant building concepts were extracted. The mai..."
9,P10,The Austrian Photovoltaic Strategy is intended to be a living document that is adjusted when con...,MISSING,"The Austrian Photovoltaic Strategy was extracted, including shortened duplicate names. However, ..."

In [13]:
market_relationship_assessments = {
    "M01": (
        "MISSING",
        (
            "No relationship represents Austria reaching 6.3 TWh of PV "
            "generation in 2023."
        ),
    ),
    "M02": (
        "MISSING",
        (
            "No relationship represents approximately 2.5 GW of new PV "
            "capacity in 2023."
        ),
    ),
    "M03": (
        "MISSING",
        (
            "No relationship represents 1 GW of new PV capacity in 2022."
        ),
    ),
    "M04": (
        "MISSING",
        (
            "The Network Infrastructure Plan and PV concepts have relationships, "
            "but no relationship preserves the 41 TWh target for 2040."
        ),
    ),
    "M05": (
        "MISSING",
        (
            "No relationship represents approximately 15 TWh of PV potential "
            "on existing and new buildings."
        ),
    ),
    "M06": (
        "MISSING",
        (
            "No relationship represents the required average PV expansion "
            "rate of approximately 2 GW per year."
        ),
    ),
    "M07": (
        "MISSING",
        (
            "No relationship represents the Transition 2040 requirement of "
            "21 TWh of PV generation in 2030."
        ),
    ),
    "M08": (
        "MISSING",
        (
            "No relationship represents the 19 TWh increase required between "
            "2020 and 2030."
        ),
    ),
    "M09": (
        "MISSING",
        (
            "Relationships connect the Renewable Expansion Act and Climate and "
            "Energy Fund to PV support, but none preserves the approximately "
            "EUR 600 million funding value for 2023."
        ),
    ),
    "M10": (
        "MISSING",
        (
            "No relationship represents PV supplying almost 10% of final "
            "electricity consumption and approximately 2% of total energy "
            "demand at the end of 2023."
        ),
    ),
}


for fact_id, (capture, notes) in market_relationship_assessments.items():
    set_relationship_capture(
        fact_id=fact_id,
        capture=capture,
        notes=notes,
    )


print("Market and numerical relationship coverage:")
print(
    recall_checklist[
        recall_checklist["fact_id"].str.startswith("M")
    ]["relationship_capture"].value_counts()
)

recall_checklist[
    recall_checklist["fact_id"].str.startswith("M")
][
    [
        "fact_id",
        "source_fact",
        "relationship_capture",
        "audit_notes",
    ]
]

Market and numerical relationship coverage:
relationship_capture
MISSING    10
Name: count, dtype: int64

,fact_id,source_fact,relationship_capture,audit_notes
10,M01,Austria reached 6.3 TWh of PV generation in 2023.,MISSING,"Photovoltaics and Austria were extracted, but 6.3 TWh of PV generation in 2023 was not represent..."
11,M02,Approximately 2.5 GW of new photovoltaic capacity was installed in Austria in 2023.,MISSING,"PV expansion and Austria were represented generally, but the 2.5 GW addition in 2023 was not rep..."
12,M03,One GW of new photovoltaic capacity was installed in Austria in 2022.,MISSING,"Photovoltaic expansion was represented generally, but the 1 GW addition in 2022 was not represen..."
13,M04,The Integrated Austrian Network Infrastructure Plan identifies 41 TWh of photovoltaic generation...,MISSING,"The Network Infrastructure Plan and Photovoltaics were extracted, but the 41 TWh by 2040 target ..."
14,M05,At least approximately 15 TWh of the 2040 PV potential is considered achievable on existing and ...,MISSING,"Buildings and PV-related concepts were extracted, but the 15 TWh building potential was not repr..."
15,M06,An average expansion rate of approximately 2 GW per year is needed to reach the 2040 PV potential.,MISSING,"PV expansion and the 2040 context appear in generated descriptions, but the required average rat..."
16,M07,The Transition 2040 scenario requires 21 TWh of photovoltaic electricity generation in 2030.,MISSING,"Transition 2040 and Photovoltaics were represented, but the 21 TWh requirement for 2030 was not ..."
17,M08,The 21 TWh requirement for 2030 represents an increase of 19 TWh compared with 2020.,MISSING,"PV expansion and the relevant years occur in generated output, but the 19 TWh increase between 2..."
18,M09,Approximately EUR 600 million was provided for PV expansion in 2023 through the Renewable Expans...,MISSING,"The Renewable Expansion Act and Climate and Energy Fund were extracted, but the approximately EU..."
19,M10,"At the end of 2023, PV supplied almost 10% of Austria's final electricity consumption and approx...",MISSING,"Photovoltaics and Austrian energy concepts were extracted, but the approximately 10% electricity..."

In [14]:
technical_relationship_assessments = {
    "T01": (
        "PARTIAL",
        (
            "The distribution grid is connected to the broader electricity "
            "grid, and digitalization appears in other relationships. However, "
            "the specific relationship that distribution-grid digitalization "
            "supports decentralized renewable integration is missing."
        ),
    ),
    "T02": (
        "PARTIAL",
        (
            "The grid is connected to smart energy management and storage "
            "solutions for handling PV generation. However, the explicit fact "
            "that PV peaks can no longer always be completely absorbed by the "
            "public grid is not preserved."
        ),
    ),
    "T03": (
        "PARTIAL",
        (
            "Smart local energy management is connected to the grid and customer "
            "installations for balancing and PV optimization. Storage and "
            "self-consumption are not completely preserved in one supported "
            "relationship."
        ),
    ),
    "T04": (
        "PARTIAL",
        (
            "Photovoltaics has separate relationships with some energy "
            "technologies, including hydrogen-related systems. The complete "
            "synergistic integration with e-mobility, heat pumps, hydrogen "
            "and storage is fragmented rather than represented as one fact."
        ),
    ),
    "T05": (
        "MISSING",
        (
            "No relationship represents east-west-oriented or vertical PV "
            "installations as methods for improving generation during shoulder "
            "and winter periods."
        ),
    ),
    "T06": (
        "FULL",
        (
            "Relationships explicitly represent Agri-PV as combined agricultural "
            "and photovoltaic land use and mention improved land-use efficiency. "
            "The essential source meaning is preserved."
        ),
    ),
    "T07": (
        "PARTIAL",
        (
            "Relationships connect open-space PV with biodiversity installations "
            "and ecological enhancement. However, the requirement to follow "
            "defined ecological criteria is not fully preserved."
        ),
    ),
    "T08": (
        "PARTIAL",
        (
            "Federal buildings are identified as targets for PV deployment, but "
            "the conditions that deployment should occur only where technically "
            "and economically feasible are missing."
        ),
    ),
    "T09": (
        "PARTIAL",
        (
            "Energy communities are connected to PV and shared storage, but "
            "the complete combination of storage, consumption flexibility, "
            "real-time monitoring and control is not represented."
        ),
    ),
    "T10": (
        "PARTIAL",
        (
            "PV circular economy, repair and recycling appear in relationships, "
            "but resource efficiency, durability, reuse and the full research "
            "objective are not represented together."
        ),
    ),
}


for fact_id, (capture, notes) in technical_relationship_assessments.items():
    set_relationship_capture(
        fact_id=fact_id,
        capture=capture,
        notes=notes,
    )


print("Technical relationship coverage:")
print(
    recall_checklist[
        recall_checklist["fact_id"].str.startswith("T")
    ]["relationship_capture"].value_counts()
)

recall_checklist[
    recall_checklist["fact_id"].str.startswith("T")
][
    [
        "fact_id",
        "source_fact",
        "relationship_capture",
        "audit_notes",
    ]
]

Technical relationship coverage:
relationship_capture
PARTIAL    8
MISSING    1
FULL       1
Name: count, dtype: int64

,fact_id,source_fact,relationship_capture,audit_notes
20,T01,Digitalization of the distribution grid is important for integrating renewable and decentralized...,PARTIAL,"The distribution grid was extracted, but digitalization specifically as a technical enabler of d..."
21,T02,Photovoltaic generation peaks can no longer always be completely absorbed by the public electric...,PARTIAL,"The electricity grid and Photovoltaics were extracted, but PV generation peaks and the grid's in..."
22,T03,Smart local energy management and storage can manage generation and consumption peaks and increa...,PARTIAL,"Smart local energy management and storage-related concepts were extracted, but self-consumption ..."
23,T04,"PV should operate synergistically with electric mobility, heat pumps, hydrogen and other generat...",PARTIAL,"Photovoltaics, e-mobility, heat pumps, hydrogen and storage-related technologies were extracted...."
24,T05,East-west-oriented and vertical PV installations can provide higher PV yields during shoulder an...,MISSING,"General PV concepts were extracted, but neither east-west-oriented PV nor vertical PV was repres..."
25,T06,Agri-PV enables combined agricultural and photovoltaic use and can increase land-use efficiency.,FULL,"Agri-PV installations were extracted, but agricultural dual use and land-use efficiency were not..."
26,T07,Open-space PV installations should be designed as biodiversity installations in accordance with ...,PARTIAL,"Open-space PV and several biodiversity-PV concepts were extracted, but the requirement to follow..."
27,T08,PV systems should be installed on federal buildings wherever technically and economically possible.,PARTIAL,"Federal buildings and PV systems were extracted, but the technical and economic feasibility cond..."
28,T09,"Energy communities should be further developed using storage, consumption flexibility, real-time...",PARTIAL,"Energy communities, storage and flexibility concepts were extracted, but real-time operational m..."
29,T10,"PV research should address resource efficiency, durability, repairability, reuse and recycling o...",PARTIAL,"PV circular economy and repair were extracted, but resource efficiency, durability, reuse and re..."

In [15]:
print("Overall relationship coverage:")
print(recall_checklist["relationship_capture"].value_counts())

print()
print("Relationship coverage by category:")
print(
    pd.crosstab(
        recall_checklist["category"],
        recall_checklist["relationship_capture"],
    )
)

Overall relationship coverage:
relationship_capture
MISSING    15
PARTIAL    13
FULL        2
Name: count, dtype: int64

Relationship coverage by category:
relationship_capture  FULL  MISSING  PARTIAL
category
MARKET_NUMERICAL         0       10        0
POLICY                   1        4        5
TECHNICAL                1        1        8

In [16]:
def classify_overall_capture(row):
    if row["text_unit_capture"] != "YES":
        return "MISSING_BEFORE_EXTRACTION"

    if (
        row["entity_capture"] == "FULL"
        and row["relationship_capture"] == "FULL"
    ):
        return "FULLY_STRUCTURED"

    if (
        row["entity_capture"] != "FULL"
        and row["relationship_capture"] == "FULL"
    ):
        return "RELATIONSHIP_TEXT_BUT_ENTITY_INCOMPLETE"

    if row["relationship_capture"] == "PARTIAL":
        return "PARTIALLY_STRUCTURED"

    if (
        row["relationship_capture"] == "MISSING"
        and row["entity_capture"] in ["FULL", "PARTIAL"]
    ):
        return "ENTITY_ONLY"

    return "MISSING_FROM_GRAPH"


recall_checklist["overall_classification"] = (
    recall_checklist.apply(
        classify_overall_capture,
        axis=1,
    )
)

print("Overall fact-level classifications:")
print(
    recall_checklist[
        "overall_classification"
    ].value_counts()
)

print()
print("Overall classifications by category:")
print(
    pd.crosstab(
        recall_checklist["category"],
        recall_checklist["overall_classification"],
    )
)

Overall fact-level classifications:
overall_classification
ENTITY_ONLY                                14
PARTIALLY_STRUCTURED                       13
FULLY_STRUCTURED                            1
MISSING_FROM_GRAPH                          1
RELATIONSHIP_TEXT_BUT_ENTITY_INCOMPLETE     1
Name: count, dtype: int64

Overall classifications by category:
overall_classification  ENTITY_ONLY  FULLY_STRUCTURED  MISSING_FROM_GRAPH  \
category
MARKET_NUMERICAL                 10                 0                   0
POLICY                            4                 1                   0
TECHNICAL                         0                 0                   1

overall_classification  PARTIALLY_STRUCTURED  \
category
MARKET_NUMERICAL                           0
POLICY                                     5
TECHNICAL                                  8

overall_classification  RELATIONSHIP_TEXT_BUT_ENTITY_INCOMPLETE
category
MARKET_NUMERICAL                                              0
POLICY                                                        0
TECHNICAL                                                     1

In [17]:
recall_output_path = (
    inspection_dir
    / "14_recall_coverage_checklist.csv"
)

recall_checklist.to_csv(
    recall_output_path,
    index=False,
    encoding="utf-8-sig",
)

print("Saved to:", recall_output_path)
print("Rows saved:", len(recall_checklist))

Saved to: C:\Users\HP-ZBOOK i7\graphrag_test\pilot_01\inspection\14_recall_coverage_checklist.csv
Rows saved: 30

# Stage 8 — Recall and Missing-Information Audit

## Objective

The previous entity and relationship audits evaluated the correctness of information generated by GraphRAG. This stage examined the opposite direction:

> How much important information from the original Austrian Photovoltaic Strategy was successfully represented in the graph?

This is a checklist-based recall or coverage assessment. It does not measure the recall of every sentence in the 44-page document.

## Method

A reference checklist of 30 important source facts was manually constructed from the original PDF.

The checklist contained:

| Category                     | Number of facts |
| ---------------------------- | --------------: |
| Policy and regulatory        |              10 |
| Market and numerical         |              10 |
| Technical and implementation |              10 |
| **Total**                    |          **30** |

The checklist included major targets, policies, measurements, technical requirements and implementation measures.

Every fact was traced through the following pipeline:

```text
Original PDF
    ↓
GraphRAG text units
    ↓
Extracted entities
    ↓
Extracted relationships
```

Each stage was assessed separately. Entity and relationship capture used the following classifications:

```text
FULL
PARTIAL
MISSING
```

A final fact-level classification was then assigned:

```text
FULLY_STRUCTURED
RELATIONSHIP_TEXT_BUT_ENTITY_INCOMPLETE
PARTIALLY_STRUCTURED
ENTITY_ONLY
MISSING_FROM_GRAPH
```

## Text-unit coverage

| Text-unit result | Number | Percentage |
| ---------------- | -----: | ---------: |
| `YES`            |     30 |     100.0% |
| `PARTIAL`        |      0 |       0.0% |
| `NO`             |      0 |       0.0% |
| **Total**        | **30** | **100.0%** |

All 30 selected facts occurred completely within at least one of the 17 text units.

This indicates that the selected policy, numerical and technical facts survived PDF conversion and chunking. Therefore, later failures cannot primarily be attributed to complete information loss before entity extraction.

This does not mean that chunking was perfect. The earlier chunking audit identified broken semantic boundaries, repeated overlap, mixed sections and a low-value final chunk. Nevertheless, the evidence required for all 30 checklist facts remained available to the extraction model.

## Entity coverage

| Entity capture | Number | Percentage |
| -------------- | -----: | ---------: |
| `FULL`         |      4 |      13.3% |
| `PARTIAL`      |     25 |      83.3% |
| `MISSING`      |      1 |       3.3% |
| **Total**      | **30** | **100.0%** |

Entity coverage by category was:

| Category             | Full | Partial | Missing |
| -------------------- | ---: | ------: | ------: |
| Policy               |    3 |       7 |       0 |
| Market and numerical |    0 |      10 |       0 |
| Technical            |    1 |       8 |       1 |

GraphRAG usually extracted the general subjects appearing in the source facts. Examples include Austria, Photovoltaics, the Renewable Expansion Act, RED III, the Climate and Energy Fund, the electricity grid and energy communities.

However, important components were frequently absent or represented only inside generated descriptions.

These missing components included:

* numerical values;
* measurement units;
* target years;
* eligibility thresholds;
* policy conditions;
* technical qualifications;
* implementation constraints.

All ten market and numerical facts were only partially represented at the entity level. GraphRAG did not create dedicated entities for important measurements and targets such as:

```text
6.3 TWh in 2023
2.5 GW in 2023
41 TWh by 2040
15 TWh on buildings
2 GW per year
21 TWh in 2030
EUR 600 million in 2023
```

This result strongly supports the need for controlled `TARGET` and `MARKET_METRIC` categories.

## Relationship coverage

| Relationship capture | Number | Percentage |
| -------------------- | -----: | ---------: |
| `FULL`               |      2 |       6.7% |
| `PARTIAL`            |     13 |      43.3% |
| `MISSING`            |     15 |      50.0% |
| **Total**            | **30** | **100.0%** |

Relationship coverage by category was:

| Category             | Full | Partial | Missing |
| -------------------- | ---: | ------: | ------: |
| Policy               |    1 |       5 |       4 |
| Market and numerical |    0 |       0 |      10 |
| Technical            |    1 |       8 |       1 |

Only two selected facts had their essential meaning fully preserved in a relationship description.

Half of the checklist facts were missing as complete relationships. Another 43.3% were represented only partially.

The most severe weakness concerned market and numerical information. None of the ten selected quantitative facts was represented as a complete relationship.

For example, GraphRAG extracted entities related to Austria, Photovoltaics and the Integrated Austrian Network Infrastructure Plan. However, it did not create a structured fact equivalent to:

```text
Integrated Austrian Network Infrastructure Plan
    → HAS_TARGET
    → 41 TWh of PV generation by 2040
```

The number, unit and target year remained available in the text units but disappeared from the structured relationship layer.

## Overall fact-level coverage

| Overall classification                    | Number | Percentage |
| ----------------------------------------- | -----: | ---------: |
| `ENTITY_ONLY`                             |     14 |      46.7% |
| `PARTIALLY_STRUCTURED`                    |     13 |      43.3% |
| `FULLY_STRUCTURED`                        |      1 |       3.3% |
| `RELATIONSHIP_TEXT_BUT_ENTITY_INCOMPLETE` |      1 |       3.3% |
| `MISSING_FROM_GRAPH`                      |      1 |       3.3% |
| **Total**                                 | **30** | **100.0%** |

Only one of the 30 facts was fully represented through both complete entities and a complete relationship.

One additional fact had its meaning preserved in relationship text, but its entity representation remained incomplete.

Fourteen facts produced relevant entities but no relationship that preserved the complete source statement.

Thirteen facts were represented by incomplete relationships that omitted an important value, qualification, condition or technical component.

## Representative evidence chains

### Example 1 — 41 TWh PV potential by 2040

**Source evidence:** The Integrated Austrian Network Infrastructure Plan identifies 41 TWh of photovoltaic generation potential by 2040.

**Text-unit result:** Fully present.

**Entity result:** The infrastructure plan and Photovoltaics were extracted, but 41 TWh by 2040 was not represented as a dedicated target.

**Relationship result:** No relationship preserves the value, unit and target year.

**Overall result:** `ENTITY_ONLY`

**Likely failure stage:** Entity and relationship extraction schema.

### Example 2 — Renewable electricity target for 2030

**Source evidence:** Austria aims to cover total electricity consumption nationally and on balance with 100% renewable energy from 2030.

**Text-unit result:** Fully present.

**Entity result:** Austria and the Renewable Expansion Act were extracted, but the complete target was not represented as a controlled target entity.

**Relationship result:** Relationships involving Austria and the Act exist, but none preserves the 100% target and 2030 deadline.

**Overall result:** `ENTITY_ONLY`

**Likely failure stage:** Target extraction and controlled relationship construction.

### Example 3 — Condominium Act amendment

**Source evidence:** The 2022 amendment made PV installation on terraced houses and individual buildings easier.

**Text-unit result:** Fully present.

**Entity result:** The law, PV systems and relevant building concepts were extracted.

**Relationship result:** GraphRAG explicitly connected the amendment with easier PV installation and terraced houses.

**Overall result:** `FULLY_STRUCTURED`

This was the strongest example of successful fact capture.

### Example 4 — East-west and vertical PV orientation

**Source evidence:** East-west-oriented and vertical PV installations can broaden periods of high PV generation, including shoulder and winter periods.

**Text-unit result:** Fully present.

**Entity result:** Neither east-west-oriented PV nor vertical PV was extracted as a dedicated entity.

**Relationship result:** No corresponding relationship was found.

**Overall result:** `MISSING_FROM_GRAPH`

**Likely failure stage:** Technical entity identification.

### Example 5 — Agri-PV dual use

**Source evidence:** Agri-PV combines agricultural use with photovoltaic generation and increases land-use efficiency.

**Text-unit result:** Fully present.

**Entity result:** Agri-PV was extracted, but land-use efficiency was not represented as a dedicated controlled entity.

**Relationship result:** The relationship description preserved agricultural dual use and improved land-use efficiency.

**Overall result:** `RELATIONSHIP_TEXT_BUT_ENTITY_INCOMPLETE`

## Pipeline diagnosis

The recall audit indicates the following information flow:

```text
Original source facts             30
        ↓
Facts preserved in text units     30
        ↓
Facts with complete entities       4
        ↓
Facts with complete relationships  2
        ↓
Fully structured facts             1
```

The major loss of structure occurred after chunking.

The dominant causes were:

1. Absence of entity types for targets and market metrics.
2. Failure to represent values, units and dates structurally.
3. Free-text relationships rather than controlled predicates.
4. Loss of qualifications such as “planned,” “where feasible,” “approximately,” or “by 2040.”
5. Fragmentation of one source fact across several generic entities and relationships.
6. Technical details being left inside source text rather than becoming graph concepts.

## Interpretation

GraphRAG demonstrated high textual coverage but low structured fact coverage.

The system usually received and retained important source information in its text units. It also frequently recognized the general topics involved. However, recognizing the topic was not sufficient to construct an explainable domain knowledge graph.

For the intended solar-market KG, the difference between these statements is important:

```text
Photovoltaics is connected to Austria.
```

and:

```text
Austria
    → HAS_TARGET
    → 41 TWh of PV generation by 2040
```

The first is a broad thematic association. The second is a structured, source-grounded and queryable policy fact.

Pilot 01 produced many relationships of the first kind and relatively few complete facts of the second kind.

## Methodological limitations

The 30 facts were deliberately selected as important policy, market and technical facts. They were not a simple random sample of every statement in the document.

Therefore, the results should be described as:

```text
checklist-based recall
```

or:

```text
sample-based structured coverage
```

They should not be presented as the exact recall of the complete 44-page source.

The assessment also distinguishes structured capture from textual mention. A value appearing inside a text unit, entity description or community report does not necessarily mean that it was represented as a queryable knowledge-graph fact.

## Stage 8 conclusion

The original PDF and text-unit stages preserved all 30 selected facts. Nevertheless, only one fact was fully represented through complete entities and a complete relationship.

The most severe false-negative problem concerns numerical targets and market indicators. None of the ten selected quantitative facts became a complete structured relationship.

The results indicate that PDF conversion and chunking were not the principal causes of low structured recall. The main losses occurred during entity identification, entity typing and relationship construction.

Pilot 02 should therefore test:

* explicit `TARGET` and `MARKET_METRIC` entity types;
* structured fields for value, unit, base year and target year;
* domain-specific examples in the extraction prompt;
* controlled relationship predicates;
* preservation of modal language and implementation conditions;
* provenance from every controlled fact to its supporting text unit.

The results support treating GraphRAG as a useful textual and thematic extraction layer, but not as a sufficiently controlled fact-extraction system without additional schema guidance and downstream validation.