# GraphRAG Inspection Viewer

This notebook loads **all files from the `inspection` folder** created for the Austrian PV Strategy pilot.

Place this notebook inside:

`C:\Users\HP-ZBOOK i7\graphrag_test\pilot_01`

The expected folder structure is:

```text
pilot_01/
├── inspection/
│   ├── 00_summary.txt
│   ├── 01_entities_all.csv
│   ├── ...
│   └── 13_community_report_review.csv
└── inspection_viewer.ipynb
```

This notebook only reads local files. It does **not** call OpenRouter or GraphRAG.

In [2]:
from pathlib import Path
import pandas as pd
from IPython.display import display

INSPECTION = Path(r"C:\Users\HP-ZBOOK i7\graphrag_test\pilot_01\inspection")

print("Inspection folder:", INSPECTION)
print("Folder exists:", INSPECTION.exists())

datasets = {}

for file in sorted(INSPECTION.glob("*.csv")):
    df = pd.read_csv(file, encoding="utf-8-sig")
    datasets[file.name] = df

print("\nImported datasets:")

for name, df in datasets.items():
    print(f"{name}: {len(df)} rows")

print("\nTotal CSV files imported:", len(datasets))

Inspection folder: C:\Users\HP-ZBOOK i7\graphrag_test\pilot_01\inspection
Folder exists: True

Imported datasets:
01_entities_all.csv: 312 rows
02_entity_type_counts.csv: 4 rows
03_entity_review.csv: 312 rows
04_relationships_all.csv: 414 rows
05_relationship_review.csv: 414 rows
06_communities_all.csv: 62 rows
07_community_reports_all.csv: 62 rows
08_documents_all.csv: 1 rows
09_text_units_all.csv: 17 rows
10_possible_duplicates.csv: 2 rows
11_top_connected_entities.csv: 30 rows
12_top_relationships.csv: 50 rows
13_community_report_review.csv: 62 rows

Total CSV files imported: 13

## 1. Setup and load every inspection file

In [23]:
from pathlib import Path
import pandas as pd
from IPython.display import display

ROOT = Path.cwd()
INSPECTION = ROOT / "inspection"

print("Notebook folder:", ROOT)
print("Inspection folder:", INSPECTION)
print("Inspection folder exists:", INSPECTION.exists())

if not INSPECTION.exists():
    raise FileNotFoundError(
        "The inspection folder was not found. "
        "Place this notebook inside pilot_01."
    )

Notebook folder: c:\Users\HP-ZBOOK i7\graphrag_test\pilot_01
Inspection folder: c:\Users\HP-ZBOOK i7\graphrag_test\pilot_01\inspection
Inspection folder exists: True

In [24]:
# Load all CSV files automatically
datasets = {}

for path in sorted(INSPECTION.glob("*.csv")):
    try:
        datasets[path.name] = pd.read_csv(path, encoding="utf-8-sig")
    except UnicodeDecodeError:
        datasets[path.name] = pd.read_csv(path)

print(f"Loaded {len(datasets)} CSV datasets.\n")

for name, df in datasets.items():
    print(f"{name:40s} {len(df):>6} rows x {len(df.columns):>3} columns")

Loaded 13 CSV datasets.

01_entities_all.csv                         312 rows x   8 columns
02_entity_type_counts.csv                     4 rows x   2 columns
03_entity_review.csv                        312 rows x  12 columns
04_relationships_all.csv                    414 rows x   8 columns
05_relationship_review.csv                  414 rows x  14 columns
06_communities_all.csv                       62 rows x  12 columns
07_community_reports_all.csv                 62 rows x  15 columns
08_documents_all.csv                          1 rows x   7 columns
09_text_units_all.csv                        17 rows x   8 columns
10_possible_duplicates.csv                    2 rows x   6 columns
11_top_connected_entities.csv                30 rows x   5 columns
12_top_relationships.csv                     50 rows x   4 columns
13_community_report_review.csv               62 rows x  18 columns

## 2. Read the summary file

In [25]:
summary_path = INSPECTION / "00_summary.txt"

if summary_path.exists():
    print(summary_path.read_text(encoding="utf-8"))
else:
    print("00_summary.txt was not found.")

======================================================================
GRAPH RAG FULL INSPECTION
Austrian Photovoltaic Strategy 2024
======================================================================

DOCUMENTS
Rows: 1
Columns: id, human_readable_id, title, text, text_unit_ids, creation_date, raw_data

TEXT_UNITS
Rows: 17
Columns: id, human_readable_id, text, n_tokens, document_id, entity_ids, relationship_ids, covariate_ids

ENTITIES
Rows: 312
Columns: id, human_readable_id, title, type, description, text_unit_ids, frequency, degree

RELATIONSHIPS
Rows: 414
Columns: id, human_readable_id, source, target, description, weight, combined_degree, text_unit_ids

COMMUNITIES
Rows: 62
Columns: id, human_readable_id, community, level, parent, children, title, entity_ids, relationship_ids, text_unit_ids, period, size

COMMUNITY_REPORTS
Rows: 62
Columns: id, human_readable_id, community, level, parent, children, title, summary, full_content, rank, rating_explanation, findings, full_content_json, period, size

======================================================================
INDEXING STATISTICS
======================================================================
Total runtime: 197.46940207481384 seconds
Number of documents: 1

======================================================================
ENTITY TYPE COUNTS
======================================================================
ORGANIZATION: 142
EVENT: 121
PERSON: 25
GEO: 24

## 3. Helper: view any dataset by filename

In [26]:
def view(filename, rows=20):
    if filename not in datasets:
        print("Dataset not found:", filename)
        print("\nAvailable datasets:")
        for name in datasets:
            print(" -", name)
        return

    df = datasets[filename]

    print(filename)
    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")
    print("\nColumn names:")
    print(list(df.columns))
    print()

    display(df.head(rows))

## 4. All entities

In [27]:
view("01_entities_all.csv", rows=30)

01_entities_all.csv
Rows: 312
Columns: 8

Column names:
['id', 'human_readable_id', 'title', 'type', 'description', 'text_unit_ids', 'frequency', 'degree']

,id,human_readable_id,title,type,description,text_unit_ids,frequency,degree
0,cb0a1b84-f9a3-4404-9807-afa3d1e6c3af,0,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,EVENT,"The ""Österreichische Photovoltaik-Strategie"" (...",['d7219f76b31818b7b13bf08dda81003d752e53f76608...,14,39
1,822d0b21-2432-4dfc-9d1f-665425d28e8b,1,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",ORGANIZATION,"The ""Bundesministerium für Klimaschutz, Umwelt...",['d7219f76b31818b7b13bf08dda81003d752e53f76608...,2,9
2,989f5ee5-4f8f-45bb-ae0c-fed8e87f1dbc,2,HUBERT FECHNER,PERSON,Author of the strategy document; involved in p...,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,1,2
3,1d4b9657-b1cb-4952-a417-bdb299846dd4,3,LEONORE GEWESSLER,PERSON,The Federal Minister of Austria for Climate Ac...,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,1,2
4,05c9af58-ac32-4ec6-b923-358b587e8cae,4,ÖSTERREICH,GEO,"Österreich, also known as Austria, is a Centra...",['d7219f76b31818b7b13bf08dda81003d752e53f76608...,15,82
5,00d38e7b-8bbe-4593-9fe9-df5bf6fb7427,5,WIEN,GEO,"WIEN is the German name for Vienna, the capita...",['d7219f76b31818b7b13bf08dda81003d752e53f76608...,3,8
6,37e2bb35-a727-40e3-b466-b12998e333aa,6,ERNEUERBAREN-AUSBAU-GESETZ (EAG),EVENT,"The ERNEUERBAREN-AUSBAU-GESETZ (EAG), known in...",['d7219f76b31818b7b13bf08dda81003d752e53f76608...,2,5
7,672d47ca-35bf-4a7a-819f-56940ff891e8,7,INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTRUKTU...,EVENT,The Integrated Austrian Network Infrastructure...,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,1,1
8,c579a318-d4d8-48b0-a35d-59fb0ca93bf4,8,PHOTOVOLTAIK (PV),EVENT,The technological process of converting solar ...,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,1,4
9,8a7a07f7-e526-4c84-8dcc-ff6f50a8e68f,9,CAJETAN PERWEIN,PERSON,Cajetan Perwein is credited as a photographer ...,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,1,1
10,a904e0ff-8af4-4090-9452-b6ee49f26cb8,10,BMK,ORGANIZATION,"BMK, the commonly used abbreviation for the Au...",['d7219f76b31818b7b13bf08dda81003d752e53f76608...,7,16
11,f8a6b069-bd80-45ff-ad46-3e77170d42aa,11,EU-ERNEUERBAREN-RICHTLINIE (RED III),ORGANIZATION,The EU Renewable Energy Directive (RED III) is...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,1,2
12,6f6d3545-ea48-48d4-b8f4-11deb32ff025,12,EUROPA,GEO,EUROPA (Europe) is the continent where Austria...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,3,2
13,3f8fbdde-b872-4a1e-b5d9-dd3c12a82852,13,KLIMA- UND ENERGIEFONDS,ORGANIZATION,The **KLIMA- UND ENERGIEFONDS** (Climate and E...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,6,14
14,653ae6e1-b8f4-4ac9-ad5b-c443382b4508,14,ENERGIEWENDE,EVENT,"The ""Energiewende"" in Austria refers to the na...",['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,7,6
15,6247c16e-35b1-4419-9d20-48ef8ea9d823,15,KLIMANEUTRALITÄT 2040,EVENT,"KLIMANEUTRALITÄT 2040, or Climate Neutrality 2...",['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,3,3
16,9b15ab50-e67c-46c6-967c-1b7ccfdf7e83,16,PV-STRATEGIE,EVENT,The photovoltaic strategy is a coordinated pla...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,1,2
17,18bb3428-e6fa-4117-be93-b9bb9e016042,17,KLIMABONUS,ORGANIZATION,Klimabonus is a financial bonus program by the...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,1,1
18,6b284db1-5113-4ba0-bdf2-1e02b942bb70,18,ÖKOSTROMANLAGEN,ORGANIZATION,"Ökostromanlagen refers to ""green electricity p...",['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,1,1
19,baeae8f7-b787-4ca6-8621-43a4ed79b360,19,LAND,ORGANIZATION,The Land refers to the provincial or state-lev...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,1,2
20,ae04b564-127d-4a59-96dd-1a4051e71baa,20,GEMEINDE,ORGANIZATION,Gemeinde refers to local or municipal governme...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,1,3
21,1ac7596b-4607-4d4d-87ca-570bf6a4189f,21,E-CONTROL,ORGANIZATION,E-CONTROL is the official Austrian regulatory ...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,6,11
22,7fa0bcf1-518f-4a47-a7a8-eeb5e0526fcd,22,WISSENSCHAFT,ORGANIZATION,WISSENSCHAFT refers to Austria’s scientific co...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,2,5
23,a46ad470-7964-406d-92d2-363593deb5e4,23,WIRTSCHAFT,ORGANIZATION,WIRTSCHAFT refers to Austria's economic and bu...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,3,5
24,14648031-eca7-4a8c-811c-0d4e7ddd2082,24,INTERESSENSVERTRETUNGEN,ORGANIZATION,INTERESSENSVERTRETUNGEN are advocacy and inter...,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,2,4
25,f8566dd0-127d-4cdb-b79a-b9ab18c2dacd,25,INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTRUKTU...,ORGANIZATION,The INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTR...,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,4,6
26,6386da48-3d9f-4a2f-80fb-432213a3231b,26,PHOTOVOLTAIK-STRATEGIE,EVENT,Die österreichische Photovoltaik-Strategie ist...,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,1,6
27,6f2d7b9e-4a9d-4697-8dee-8c93028e957c,27,EU-EMISSIONSHANDEL,ORGANIZATION,Der EU-Emissionshandel ist das zentrale europä...,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,1,1
28,d6cc1a8e-9f0c-480e-9626-cbe42aa054ca,28,EUROPÄISCHE UNION,ORGANIZATION,"The EUROPÄISCHE UNION (European Union, EU) is ...",['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,2,4
29,cf9f9721-4bd5-4378-8aff-c27b9cf0d682,29,FORSCHUNGSRAMMENPROGRAMM,EVENT,Das Europäische Forschungsrahmenprogramm ist d...,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,1,1

## 5. Entity type counts

In [28]:
view("02_entity_type_counts.csv", rows=50)

02_entity_type_counts.csv
Rows: 4
Columns: 2

Column names:
['raw_graphrag_type', 'count']

  raw_graphrag_type  count
0      ORGANIZATION    142
1             EVENT    121
2            PERSON     25
3               GEO     24

## 6. Entity review table

This is one of the most important files.

Use it later for:
- GraphRAG raw type
- suggested controlled-schema type
- canonical entity name
- keep/reject decision
- record linkage
- review notes

In [29]:
view("03_entity_review.csv", rows=30)

03_entity_review.csv
Rows: 312
Columns: 12

Column names:
['human_readable_id', 'title', 'type', 'description', 'frequency', 'degree', 'text_unit_ids', 'suggested_schema_type', 'canonical_name', 'keep_in_controlled_kg', 'record_linkage_group', 'review_notes']

,human_readable_id,title,type,description,frequency,degree,text_unit_ids,suggested_schema_type,canonical_name,keep_in_controlled_kg,record_linkage_group,review_notes
0,0,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,EVENT,"The ""Österreichische Photovoltaik-Strategie"" (...",14,39,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
1,1,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",ORGANIZATION,"The ""Bundesministerium für Klimaschutz, Umwelt...",2,9,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
2,2,HUBERT FECHNER,PERSON,Author of the strategy document; involved in p...,1,2,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
3,3,LEONORE GEWESSLER,PERSON,The Federal Minister of Austria for Climate Ac...,1,2,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
4,4,ÖSTERREICH,GEO,"Österreich, also known as Austria, is a Centra...",15,82,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
5,5,WIEN,GEO,"WIEN is the German name for Vienna, the capita...",3,8,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
6,6,ERNEUERBAREN-AUSBAU-GESETZ (EAG),EVENT,"The ERNEUERBAREN-AUSBAU-GESETZ (EAG), known in...",2,5,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
7,7,INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTRUKTU...,EVENT,The Integrated Austrian Network Infrastructure...,1,1,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
8,8,PHOTOVOLTAIK (PV),EVENT,The technological process of converting solar ...,1,4,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
9,9,CAJETAN PERWEIN,PERSON,Cajetan Perwein is credited as a photographer ...,1,1,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
10,10,BMK,ORGANIZATION,"BMK, the commonly used abbreviation for the Au...",7,16,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
11,11,EU-ERNEUERBAREN-RICHTLINIE (RED III),ORGANIZATION,The EU Renewable Energy Directive (RED III) is...,1,2,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
12,12,EUROPA,GEO,EUROPA (Europe) is the continent where Austria...,3,2,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
13,13,KLIMA- UND ENERGIEFONDS,ORGANIZATION,The **KLIMA- UND ENERGIEFONDS** (Climate and E...,6,14,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
14,14,ENERGIEWENDE,EVENT,"The ""Energiewende"" in Austria refers to the na...",7,6,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
15,15,KLIMANEUTRALITÄT 2040,EVENT,"KLIMANEUTRALITÄT 2040, or Climate Neutrality 2...",3,3,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
16,16,PV-STRATEGIE,EVENT,The photovoltaic strategy is a coordinated pla...,1,2,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
17,17,KLIMABONUS,ORGANIZATION,Klimabonus is a financial bonus program by the...,1,1,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
18,18,ÖKOSTROMANLAGEN,ORGANIZATION,"Ökostromanlagen refers to ""green electricity p...",1,1,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
19,19,LAND,ORGANIZATION,The Land refers to the provincial or state-lev...,1,2,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
20,20,GEMEINDE,ORGANIZATION,Gemeinde refers to local or municipal governme...,1,3,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
21,21,E-CONTROL,ORGANIZATION,E-CONTROL is the official Austrian regulatory ...,6,11,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
22,22,WISSENSCHAFT,ORGANIZATION,WISSENSCHAFT refers to Austria’s scientific co...,2,5,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
23,23,WIRTSCHAFT,ORGANIZATION,WIRTSCHAFT refers to Austria's economic and bu...,3,5,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
24,24,INTERESSENSVERTRETUNGEN,ORGANIZATION,INTERESSENSVERTRETUNGEN are advocacy and inter...,2,4,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,NaN,NaN,NaN,NaN,NaN
25,25,INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTRUKTU...,ORGANIZATION,The INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTR...,4,6,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,NaN,NaN,NaN,NaN,NaN
26,26,PHOTOVOLTAIK-STRATEGIE,EVENT,Die österreichische Photovoltaik-Strategie ist...,1,6,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,NaN,NaN,NaN,NaN,NaN
27,27,EU-EMISSIONSHANDEL,ORGANIZATION,Der EU-Emissionshandel ist das zentrale europä...,1,1,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,NaN,NaN,NaN,NaN,NaN
28,28,EUROPÄISCHE UNION,ORGANIZATION,"The EUROPÄISCHE UNION (European Union, EU) is ...",2,4,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,NaN,NaN,NaN,NaN,NaN
29,29,FORSCHUNGSRAMMENPROGRAMM,EVENT,Das Europäische Forschungsrahmenprogramm ist d...,1,1,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,NaN,NaN,NaN,NaN,NaN

## 7. All relationships

In [30]:
view("04_relationships_all.csv", rows=30)

04_relationships_all.csv
Rows: 414
Columns: 8

Column names:
['id', 'human_readable_id', 'source', 'target', 'description', 'weight', 'combined_degree', 'text_unit_ids']

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids
0,ee487943-e36d-4146-8e2e-b7a9a1fd3067,0,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,"The BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT,...",19.0,48,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
1,e87db637-71f3-4134-8a02-954d1e518207,1,HUBERT FECHNER,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Hubert Fechner is the principal author of the ...,8.0,41,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
2,316e1382-2ca7-477e-9d9f-c5f6bab0b3ba,2,LEONORE GEWESSLER,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",Leonore Gewessler is the Federal Minister lead...,10.0,11,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
3,86b0f8da-0a86-48c8-990d-8fbbe165249b,3,LEONORE GEWESSLER,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,"Leonore Gewessler represents, promotes, and ov...",9.0,41,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
4,c2727a60-8f2d-4b7f-9fd0-25cd463e97c7,4,ÖSTERREICH,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ÖSTERREICH (Austria) is both the creator and p...,67.0,121,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
5,48dadaa4-1765-4d04-bab8-87e9047bf629,5,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",HUBERT FECHNER,Hubert Fechner authored the strategy document ...,6.0,11,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
6,dbda7288-2916-410f-95d8-54283a4ce66a,6,WIEN,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",Vienna is the seat of the Ministry and the pub...,7.0,17,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
7,34e20a8c-8899-486c-afa6-f1467d515bfb,7,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,The EAG is a backbone legal act referenced and...,9.0,44,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
8,3a9025be-b2d8-4591-ba85-1fd25a4a58d2,8,INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTRUKTU...,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,The strategy references and builds upon the PV...,8.0,40,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
9,566248fe-36d9-4a5b-ac41-3e78c624fc7b,9,PHOTOVOLTAIK (PV),ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,The entire strategy is centered on the expansi...,10.0,43,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
10,4b36de6f-cfa8-479e-b021-a0839a3eefae,10,PHOTOVOLTAIK (PV),ERNEUERBAREN-AUSBAU-GESETZ (EAG),The EAG legal framework prioritizes and enable...,8.0,9,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
11,0de6120a-0cee-4a13-9f9d-3b1a09628855,11,PHOTOVOLTAIK (PV),ÖSTERREICH,Austria aims to adopt photovoltaics at a massi...,1.0,86,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
12,9bcc28a7-bb93-405d-9481-1a03b46a1c22,12,CAJETAN PERWEIN,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Cajetan Perwein is credited for photography (f...,2.0,40,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
13,798e0770-d5e0-4b9e-b0ae-63eb3d158953,13,BMK,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...","BMK, which stands for BUNDESMINISTERIUM FÜR KL...",11.0,25,['d7219f76b31818b7b13bf08dda81003d752e53f76608...
14,0a7b5893-ad12-483f-81b2-a48bcabd624e,14,ÖSTERREICH,PHOTOVOLTAIK (PV),Austria is expanding the role of photovoltaics...,9.0,86,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
15,5fda0a6f-e7bb-4d5e-b264-bb0025e50fec,15,ÖSTERREICH,KLIMANEUTRALITÄT 2040,Austria (ÖSTERREICH) has established an ambiti...,19.0,85,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
16,ec71f566-452c-4675-a68c-be2e339f5247,16,PHOTOVOLTAIK (PV),PV-STRATEGIE,The PV-Strategie is Austria’s strategy specifi...,9.0,6,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
17,2b800bef-6f3e-4358-a1ee-4507a36d8fb9,17,PV-STRATEGIE,ENERGIEWENDE,"The PV-Strategie supports the Energiewende, wh...",8.0,8,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
18,8f136cc5-5fab-48df-95e0-d1adde8690fc,18,EU-ERNEUERBAREN-RICHTLINIE (RED III),EUROPA,RED III is a binding directive that applies to...,10.0,4,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
19,79a96624-525f-45bc-a5f5-3b4eed51e0a2,19,ÖSTERREICH,EU-ERNEUERBAREN-RICHTLINIE (RED III),Austria is obliged to fulfill the requirements...,9.0,84,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
20,afd21bac-f31e-44fe-883f-43e10808292e,20,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖSTERREICH,The EAG is an Austrian law that sets a legal a...,10.0,87,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
21,3d188ab4-e4ac-4bb2-a4d3-da1cbae4527c,21,KLIMA- UND ENERGIEFONDS,ÖSTERREICH,The Climate and Energy Fund provides crucial f...,8.0,96,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
22,1135fa09-924a-4fd4-ad10-3895fb2dee28,22,BMK,ÖSTERREICH,"BMK, or the Federal Ministry for Climate Actio...",27.0,98,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
23,6d4c7e21-a571-4dd2-93a4-349709ed1664,23,BMK,KLIMA- UND ENERGIEFONDS,BMK provides or allocates financial resources ...,7.0,30,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
24,7f955d99-4df9-40cf-87cc-2c070a88db49,24,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖKOSTROMANLAGEN,The EAG supports and incentivizes green electr...,9.0,6,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
25,3a9a1d29-c2f0-445c-b9fc-212a1b4c23c9,25,ÖSTERREICH,KLIMABONUS,The Klimabonus is paid to Austrian households ...,1.0,83,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
26,698c146f-ef83-4e16-85bf-c1ffc812d7d1,26,BUND,ÖSTERREICH,The Bund operates at the federal level within ...,8.0,96,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
27,945a5167-4938-440a-bd92-21b12dc32e4f,27,LAND,ÖSTERREICH,Land entities represent the various Austrian s...,8.0,84,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
28,fc9dc79a-d096-49c9-b8c3-1e14e447409f,28,GEMEINDE,ÖSTERREICH,"In Austria, ""Gemeinden,"" or municipalities, fu...",16.0,85,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...
29,7cdc3a21-2eca-4a5b-9542-80e5391805ba,29,E-CONTROL,ÖSTERREICH,E-Control is Austria’s national regulatory aut...,18.0,93,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...

## 8. Relationship review table

This is the second main manual-review file.

Later we can classify relationships as:
- source-supported
- inferred
- questionable
- reject

In [31]:
view("05_relationship_review.csv", rows=30)

05_relationship_review.csv
Rows: 414
Columns: 14

Column names:
['id', 'human_readable_id', 'source', 'target', 'description', 'weight', 'combined_degree', 'text_unit_ids', 'source_raw_type', 'target_raw_type', 'evidence_status', 'suggested_relation_type', 'keep_in_controlled_kg', 'review_notes']

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids,source_raw_type,target_raw_type,evidence_status,suggested_relation_type,keep_in_controlled_kg,review_notes
0,ee487943-e36d-4146-8e2e-b7a9a1fd3067,0,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,"The BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT,...",19.0,48,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,ORGANIZATION,EVENT,NaN,NaN,NaN,NaN
1,e87db637-71f3-4134-8a02-954d1e518207,1,HUBERT FECHNER,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Hubert Fechner is the principal author of the ...,8.0,41,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,PERSON,EVENT,NaN,NaN,NaN,NaN
2,316e1382-2ca7-477e-9d9f-c5f6bab0b3ba,2,LEONORE GEWESSLER,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",Leonore Gewessler is the Federal Minister lead...,10.0,11,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,PERSON,ORGANIZATION,NaN,NaN,NaN,NaN
3,86b0f8da-0a86-48c8-990d-8fbbe165249b,3,LEONORE GEWESSLER,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,"Leonore Gewessler represents, promotes, and ov...",9.0,41,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,PERSON,EVENT,NaN,NaN,NaN,NaN
4,c2727a60-8f2d-4b7f-9fd0-25cd463e97c7,4,ÖSTERREICH,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ÖSTERREICH (Austria) is both the creator and p...,67.0,121,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,GEO,EVENT,NaN,NaN,NaN,NaN
5,48dadaa4-1765-4d04-bab8-87e9047bf629,5,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",HUBERT FECHNER,Hubert Fechner authored the strategy document ...,6.0,11,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,ORGANIZATION,PERSON,NaN,NaN,NaN,NaN
6,dbda7288-2916-410f-95d8-54283a4ce66a,6,WIEN,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",Vienna is the seat of the Ministry and the pub...,7.0,17,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,GEO,ORGANIZATION,NaN,NaN,NaN,NaN
7,34e20a8c-8899-486c-afa6-f1467d515bfb,7,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,The EAG is a backbone legal act referenced and...,9.0,44,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,EVENT,EVENT,NaN,NaN,NaN,NaN
8,3a9025be-b2d8-4591-ba85-1fd25a4a58d2,8,INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTRUKTU...,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,The strategy references and builds upon the PV...,8.0,40,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,EVENT,EVENT,NaN,NaN,NaN,NaN
9,566248fe-36d9-4a5b-ac41-3e78c624fc7b,9,PHOTOVOLTAIK (PV),ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,The entire strategy is centered on the expansi...,10.0,43,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,EVENT,EVENT,NaN,NaN,NaN,NaN
10,4b36de6f-cfa8-479e-b021-a0839a3eefae,10,PHOTOVOLTAIK (PV),ERNEUERBAREN-AUSBAU-GESETZ (EAG),The EAG legal framework prioritizes and enable...,8.0,9,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,EVENT,EVENT,NaN,NaN,NaN,NaN
11,0de6120a-0cee-4a13-9f9d-3b1a09628855,11,PHOTOVOLTAIK (PV),ÖSTERREICH,Austria aims to adopt photovoltaics at a massi...,1.0,86,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,EVENT,GEO,NaN,NaN,NaN,NaN
12,9bcc28a7-bb93-405d-9481-1a03b46a1c22,12,CAJETAN PERWEIN,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Cajetan Perwein is credited for photography (f...,2.0,40,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,PERSON,EVENT,NaN,NaN,NaN,NaN
13,798e0770-d5e0-4b9e-b0ae-63eb3d158953,13,BMK,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...","BMK, which stands for BUNDESMINISTERIUM FÜR KL...",11.0,25,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,ORGANIZATION,ORGANIZATION,NaN,NaN,NaN,NaN
14,0a7b5893-ad12-483f-81b2-a48bcabd624e,14,ÖSTERREICH,PHOTOVOLTAIK (PV),Austria is expanding the role of photovoltaics...,9.0,86,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,GEO,EVENT,NaN,NaN,NaN,NaN
15,5fda0a6f-e7bb-4d5e-b264-bb0025e50fec,15,ÖSTERREICH,KLIMANEUTRALITÄT 2040,Austria (ÖSTERREICH) has established an ambiti...,19.0,85,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,GEO,EVENT,NaN,NaN,NaN,NaN
16,ec71f566-452c-4675-a68c-be2e339f5247,16,PHOTOVOLTAIK (PV),PV-STRATEGIE,The PV-Strategie is Austria’s strategy specifi...,9.0,6,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,EVENT,EVENT,NaN,NaN,NaN,NaN
17,2b800bef-6f3e-4358-a1ee-4507a36d8fb9,17,PV-STRATEGIE,ENERGIEWENDE,"The PV-Strategie supports the Energiewende, wh...",8.0,8,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,EVENT,EVENT,NaN,NaN,NaN,NaN
18,8f136cc5-5fab-48df-95e0-d1adde8690fc,18,EU-ERNEUERBAREN-RICHTLINIE (RED III),EUROPA,RED III is a binding directive that applies to...,10.0,4,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,ORGANIZATION,GEO,NaN,NaN,NaN,NaN
19,79a96624-525f-45bc-a5f5-3b4eed51e0a2,19,ÖSTERREICH,EU-ERNEUERBAREN-RICHTLINIE (RED III),Austria is obliged to fulfill the requirements...,9.0,84,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,GEO,ORGANIZATION,NaN,NaN,NaN,NaN
20,afd21bac-f31e-44fe-883f-43e10808292e,20,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖSTERREICH,The EAG is an Austrian law that sets a legal a...,10.0,87,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,EVENT,GEO,NaN,NaN,NaN,NaN
21,3d188ab4-e4ac-4bb2-a4d3-da1cbae4527c,21,KLIMA- UND ENERGIEFONDS,ÖSTERREICH,The Climate and Energy Fund provides crucial f...,8.0,96,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,ORGANIZATION,GEO,NaN,NaN,NaN,NaN
22,1135fa09-924a-4fd4-ad10-3895fb2dee28,22,BMK,ÖSTERREICH,"BMK, or the Federal Ministry for Climate Actio...",27.0,98,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,ORGANIZATION,GEO,NaN,NaN,NaN,NaN
23,6d4c7e21-a571-4dd2-93a4-349709ed1664,23,BMK,KLIMA- UND ENERGIEFONDS,BMK provides or allocates financial resources ...,7.0,30,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,ORGANIZATION,ORGANIZATION,NaN,NaN,NaN,NaN
24,7f955d99-4df9-40cf-87cc-2c070a88db49,24,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖKOSTROMANLAGEN,The EAG supports and incentivizes green electr...,9.0,6,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,EVENT,ORGANIZATION,NaN,NaN,NaN,NaN
25,3a9a1d29-c2f0-445c-b9fc-212a1b4c23c9,25,ÖSTERREICH,KLIMABONUS,The Klimabonus is paid to Austrian households ...,1.0,83,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,GEO,ORGANIZATION,NaN,NaN,NaN,NaN
26,698c146f-ef83-4e16-85bf-c1ffc812d7d1,26,BUND,ÖSTERREICH,The Bund operates at the federal level within ...,8.0,96,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,ORGANIZATION,GEO,NaN,NaN,NaN,NaN
27,945a5167-4938-440a-bd92-21b12dc32e4f,27,LAND,ÖSTERREICH,Land entities represent the various Austrian s...,8.0,84,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,ORGANIZATION,GEO,NaN,NaN,NaN,NaN
28,fc9dc79a-d096-49c9-b8c3-1e14e447409f,28,GEMEINDE,ÖSTERREICH,"In Austria, ""Gemeinden,"" or municipalities, fu...",16.0,85,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,ORGANIZATION,GEO,NaN,NaN,NaN,NaN
29,7cdc3a21-2eca-4a5b-9542-80e5391805ba,29,E-CONTROL,ÖSTERREICH,E-Control is Austria’s national regulatory aut...,18.0,93,['50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8...,ORGANIZATION,GEO,NaN,NaN,NaN,NaN

## 9. Communities

In [32]:
view("06_communities_all.csv", rows=30)

06_communities_all.csv
Rows: 62
Columns: 12

Column names:
['id', 'human_readable_id', 'community', 'level', 'parent', 'children', 'title', 'entity_ids', 'relationship_ids', 'text_unit_ids', 'period', 'size']

,id,human_readable_id,community,level,parent,children,title,entity_ids,relationship_ids,text_unit_ids,period,size
0,a438a991-b71d-469b-a1b5-20ef8ed2c8e5,0,0,0,-1,[16 17 18],Community 0,['c3251355-9488-4c60-a9ab-6be8c1c1c7ea'\n '164...,['163f4474-cccd-44af-aa9b-30d7c7f7d92b'\n '1e3...,['05802f69e17001a506260c74ca400f6a1368fbf01327...,2026-07-26,19
1,89a0b61a-0b65-430f-98f6-2580e7e8aca0,1,1,0,-1,[],Community 1,['13117ee5-b90c-4b76-8040-493a82f75bab'\n '7f2...,['15562353-e4ea-483e-af2b-2b6790c3c853'\n '2c7...,['41bd25afdc1cce74b36dd6db5e44e91354172fda1647...,2026-07-26,9
2,c01b5153-8328-46aa-a474-c9a5e37367c1,2,2,0,-1,[19 20 21 22],Community 2,['266cefa0-e9a7-467f-861d-edd83f4640b8'\n '215...,['0915d977-7c3a-4602-a1b3-e524e099b557'\n '0b4...,['23663988970639bea940978ccbd9150fd292856f2f31...,2026-07-26,20
3,bca47c41-c55b-43cb-8d78-2e9c04d3449a,3,3,0,-1,[23 24 25 26],Community 3,['54fa733a-a7c0-4381-a636-a9658fa0e87e'\n '8a8...,['077dc73a-13dd-4054-b2f1-5a225ae155d7'\n '0aa...,['23663988970639bea940978ccbd9150fd292856f2f31...,2026-07-26,12
4,063d9b6c-1392-43e8-8ff0-b709b5ca7f27,4,4,0,-1,[27 28],Community 4,['c6d4e772-b49e-41d5-9ea7-0f84b2a805ee'\n '4f4...,['0b1bd8a6-5def-4466-82c7-973c62019a02'\n '16a...,['05802f69e17001a506260c74ca400f6a1368fbf01327...,2026-07-26,12
5,97030300-0a79-4cc0-922a-7bded5ef6b8b,5,5,0,-1,[29 30 31 32 33 34 35],Community 5,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '586...,['02990fc8-a1a7-4ec9-9d12-ea19e65ee6ef'\n '0db...,['05802f69e17001a506260c74ca400f6a1368fbf01327...,2026-07-26,34
6,24ff87cd-f2b4-41ae-9537-e0e56ccbce3a,6,6,0,-1,[36 37 38 39],Community 6,['6f588fa0-b739-4da0-8b84-acfb7bf40dda'\n '00d...,['019059ec-b98f-4eb6-b9c0-1553ffa9ae88'\n '09c...,['4d221520fe7090409cfa9cda598db30683356c340ab3...,2026-07-26,14
7,df080313-8d00-40cc-b55f-af434832b77c,7,7,0,-1,[],Community 7,['5941618c-31ba-4dc7-8ec3-057ae490aabd'\n '41d...,['1eccd143-266e-469a-8809-fe231f112954'\n '200...,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,2026-07-26,7
8,fee0f963-186d-4545-b6ef-1cfe13ada4ff,8,8,0,-1,[40 41 42 43],Community 8,['f8a2b891-80cf-4a82-9115-71f503f46d34'\n 'e60...,['042f5191-40c6-43f5-b37f-e24f7effada6'\n '112...,['23663988970639bea940978ccbd9150fd292856f2f31...,2026-07-26,19
9,43d79948-58b9-4f05-9fe0-f465bcba2ca5,9,9,0,-1,[44 45 46 47],Community 9,['28ad2239-3425-467c-a5b7-d2d823e3d34d'\n '7a0...,['04ee5f0f-2e1f-4ada-a715-7be714b884b7'\n '40d...,['05802f69e17001a506260c74ca400f6a1368fbf01327...,2026-07-26,12
10,d7fddd5e-7f05-4c63-b598-224e58bd8fb1,10,10,0,-1,[],Community 10,['dfc59aae-ef38-4578-b38c-8c4b2a6d971b'\n 'fd2...,['1e393200-7fbb-4b23-b681-91cddc0dad2b'\n '378...,['9ce049a98570c6bf53cf9e547168db075af2795fa519...,2026-07-26,7
11,aeb73a3c-e28d-441f-986a-42b1b1e64a92,11,11,0,-1,[48 49 50 51],Community 11,['23a6515e-3ba4-4537-a9be-fb00a3865bc3'\n 'c45...,['0c8cf181-cbde-4143-b52a-aa05624b0afd'\n '198...,['2d9fdebd364caf6ea226dc0ee6624e0c2d54fc65848a...,2026-07-26,21
12,ff78fa54-64fa-4884-9eb6-b56f333a7234,12,12,0,-1,[],Community 12,['4f04dbb8-dbbd-4d06-b4da-223b95c93bc4'\n '562...,['54ecb8ad-507c-4aa8-8f2e-912cab880433'\n '5b8...,['06c273ec9919eb4693462fdacebd50536ccdcf47bacc...,2026-07-26,6
13,91735a18-81d8-47f2-80fe-7b03ee202ef8,13,13,0,-1,[],Community 13,['dc774b2e-a462-4966-9eb4-f8e3348675ae'\n '880...,['674c3ed4-3143-4727-a2fc-fb96eb2cd1cb'\n '870...,['dafd7f2f39e49c87969ec1360e9fae0af9de6f290655...,2026-07-26,6
14,2ab0be16-ccd2-49ba-ba9e-fa9a1f074f14,14,14,0,-1,[],Community 14,['075de7f2-8124-432f-a0a7-a07798d0bcae'\n '3dd...,['125c8991-9e5d-4262-8f54-4563ac2cd955'\n 'b57...,['23663988970639bea940978ccbd9150fd292856f2f31...,2026-07-26,3
15,9c63bea6-10c7-49ba-b457-bffc934dbca6,15,15,0,-1,[52 53 54 55 56 57 58 59],Community 15,['05c9af58-ac32-4ec6-b923-358b587e8cae'\n '381...,['0022a143-9f61-43ed-9593-28cc1c8cda8b'\n '04c...,['05802f69e17001a506260c74ca400f6a1368fbf01327...,2026-07-26,62
16,49a528d6-c95e-4f8c-9f45-a9f91ec17391,16,16,1,0,[],Community 16,['c3251355-9488-4c60-a9ab-6be8c1c1c7ea'\n '164...,['6c4ee7ac-61b1-44a9-99dc-8700f339a8ca'\n '9eb...,['05802f69e17001a506260c74ca400f6a1368fbf01327...,2026-07-26,6
17,5fbd4a22-bc34-46ad-b794-02f3ba11761e,17,17,1,0,[],Community 17,['a904e0ff-8af4-4090-9452-b6ee49f26cb8'\n '7fa...,['685f5479-026f-4e7b-9a22-76bc93cae728'\n '885...,['06c273ec9919eb4693462fdacebd50536ccdcf47bacc...,2026-07-26,9
18,3b7e252c-a8df-46b6-a0e3-01ff7b96eb77,18,18,1,0,[],Community 18,['387f0e24-f580-4221-8bbc-9ee9ad2fdb1d'\n '822...,['316e1382-2ca7-477e-9d9f-c5f6bab0b3ba'\n '7bc...,['7ae981575e185e2452d144d541d822b7725e27bc7dda...,2026-07-26,4
19,60de143d-4b9e-402d-bf17-82c1b95ae6d7,19,19,1,2,[],Community 19,['266cefa0-e9a7-467f-861d-edd83f4640b8'\n '215...,['19072728-40af-44c0-b252-e5a77905721f'\n '273...,['23663988970639bea940978ccbd9150fd292856f2f31...,2026-07-26,4
20,5d44e681-7ec8-47ae-b7c2-c08b5eb60d6f,20,20,1,2,[],Community 20,['87671c51-7ba4-4fb4-97a0-6e4dde071aaf'\n '4c4...,['0c27b0c7-952d-41ee-b07f-d5e0a41280cf'\n '244...,['41bd25afdc1cce74b36dd6db5e44e91354172fda1647...,2026-07-26,12
21,0bb9daf1-8353-45d4-96f6-18251b8f7ea8,21,21,1,2,[],Community 21,['0d10a81f-a956-41ee-aff5-1afe6357d906'\n 'da8...,['0b435199-cc9e-4b42-8ecf-ffc20fc4922d'],['e498566a78d36b3ce13304157993b9b4269045840f1d...,2026-07-26,2
22,4d8a9c04-90a9-4293-b82b-d17e115c5774,22,22,1,2,[],Community 22,['b4f74b36-edcb-4bdf-896e-86f95606ab04'\n '806...,['55ae061b-29bc-4047-84eb-8f8bb23a9145'],['e498566a78d36b3ce13304157993b9b4269045840f1d...,2026-07-26,2
23,7d4fce4c-de39-4185-8297-1477ed2a100a,23,23,1,3,[],Community 23,['54fa733a-a7c0-4381-a636-a9658fa0e87e'\n '8a8...,['077dc73a-13dd-4054-b2f1-5a225ae155d7'\n 'e7d...,['7a01190bcf30936758d004f89d7553c62632e91427f9...,2026-07-26,3
24,48c3e36b-152c-46c5-a252-d6cd9a89ffeb,24,24,1,3,[],Community 24,['88074642-e56c-4151-a3a7-3faba674981c'\n '146...,['78ae91a7-8fac-49fa-a52b-61e5cf27c86e'\n '9d4...,['23663988970639bea940978ccbd9150fd292856f2f31...,2026-07-26,4
25,e7e0017a-103e-4971-9b10-12a8fa44b4b6,25,25,1,3,[],Community 25,['f19d5f3d-ba6e-4b4c-835d-7e5a5c76d5ca'\n 'fba...,['a1df905d-f4ef-494a-a6c4-76a91ca6c06f'\n 'f2d...,['6a1a5132f360531b1174e0eac2b2c5b6ece3b0771a80...,2026-07-26,3
26,06501ed6-5ee3-46c1-9041-52b1723f71c0,26,26,1,3,[],Community 26,['b343cef7-f035-475f-83d7-4c66f9d50518'\n '685...,['0aa2721d-8355-4e44-8d25-a8c03cd69154'],['7a01190bcf30936758d004f89d7553c62632e91427f9...,2026-07-26,2
27,62e0a975-e429-4287-ad4e-12022caeef44,27,27,1,4,[],Community 27,['c6d4e772-b49e-41d5-9ea7-0f84b2a805ee'\n '4f4...,['0b1bd8a6-5def-4466-82c7-973c62019a02'\n '16a...,['05802f69e17001a506260c74ca400f6a1368fbf01327...,2026-07-26,8
28,e0389326-7a02-49df-a8f8-7710c6d09105,28,28,1,4,[],Community 28,['65e29d8f-cf08-4e8a-bdec-d0e401b1218e'\n '060...,['41e89949-0bc6-4edf-a904-e7038e8a2297'\n '8e9...,['6927535991c09031efd0df39ec21591dd3bb460da14c...,2026-07-26,4
29,2b78b271-7ead-4947-8c53-c858394d274b,29,29,1,5,[60 61],Community 29,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '586...,['02990fc8-a1a7-4ec9-9d12-ea19e65ee6ef'\n '2a1...,['23663988970639bea940978ccbd9150fd292856f2f31...,2026-07-26,13

## 10. Community reports

In [33]:
view("07_community_reports_all.csv", rows=20)

07_community_reports_all.csv
Rows: 62
Columns: 15

Column names:
['id', 'human_readable_id', 'community', 'level', 'parent', 'children', 'title', 'summary', 'full_content', 'rank', 'rating_explanation', 'findings', 'full_content_json', 'period', 'size']

,id,human_readable_id,community,level,parent,children,title,summary,full_content,rank,rating_explanation,findings,full_content_json,period,size
0,a13b29e2a420bd349c8f9109e6022a7eff9c597d717531...,60,60,2,29,[],Austrian Federal Government and National PV De...,This community centers on the Austrian Federal...,# Austrian Federal Government and National PV ...,8.0,The impact severity rating is high because the...,[{'explanation': 'The Austrian Federal Governm...,"{\n ""title"": ""Austrian Federal Government a...",2026-07-26,2
1,26230d3544d875be82557e5e8a2d80bb6e50c105db077b...,61,61,2,29,[],Austrian Photovoltaic Strategy Leadership and ...,This community centers around Austria's nation...,# Austrian Photovoltaic Strategy Leadership an...,8.5,The community commands high impact due to its ...,"[{'explanation': 'The ""Österreichische Photovo...","{\n ""title"": ""Austrian Photovoltaic Strateg...",2026-07-26,11
2,4cfc69a997bb9b15ad32bfa02086d886bfddcb1f76ce50...,16,16,1,0,[],E-Control and Austria's Grid Connection Action...,"This community centers on E-Control, Austria’s...",# E-Control and Austria's Grid Connection Acti...,8.5,The impact severity rating is high due to E-Co...,"[{'explanation': ""E-Control occupies a central...","{\n ""title"": ""E-Control and Austria's Grid ...",2026-07-26,6
3,003b89cc2b10773b1215b9f1c80d85aace49d6e3a4795f...,17,17,1,0,[],Austria’s Photovoltaic and Energy Transition S...,This community comprises key Austrian institut...,# Austria’s Photovoltaic and Energy Transition...,8.0,The impact severity rating is high due to the ...,[{'explanation': 'BMK (the Austrian Federal Mi...,"{\n ""title"": ""Austria’s Photovoltaic and En...",2026-07-26,9
4,6c92ae3c680eb80aff4de648ad303a3d98042d7efd5516...,18,18,1,0,[],Austrian Federal Ministry for Climate Action a...,This community centers around Austria's Federa...,# Austrian Federal Ministry for Climate Action...,8.5,The BMK community poses high impact due to its...,"[{'explanation': ""The Bundesministerium für Kl...","{\n ""title"": ""Austrian Federal Ministry for...",2026-07-26,4
5,e7194ecf611b10a2fb9ba5600ea1208399a1cbe30a57af...,19,19,1,2,[],Austrian Renewable Expansion Act and AGRI-PV-A...,This community centers on the implementation o...,# Austrian Renewable Expansion Act and AGRI-PV...,8.5,The community has a high impact severity ratin...,[{'explanation': 'The Austrian Renewable Expan...,"{\n ""title"": ""Austrian Renewable Expansion ...",2026-07-26,4
6,4517b31e6c628891cde69690d418e600c1c4db5297bac0...,20,20,1,2,[],Austria's Photovoltaic Sector and Energy Marke...,This community centers on Austria’s rapidly ev...,# Austria's Photovoltaic Sector and Energy Mar...,8.5,The severity rating is high due to the communi...,"[{'explanation': 'PV-ANLAGE installations, enc...","{\n ""title"": ""Austria's Photovoltaic Sector...",2026-07-26,12
7,ab32d2277b97f91d2d5732a8f957b8a7b550ef8f66b7e3...,21,21,1,2,[],Austrian Biodiversitäts-Solarpark and Freifläc...,This community encompasses Austria's effort to...,# Austrian Biodiversitäts-Solarpark and Freifl...,8.5,"The community’s integrated, dual-focus approac...",[{'explanation': 'Both FREIFLÄCHEN-BIODIVERSIT...,"{\n ""title"": ""Austrian Biodiversitäts-Solar...",2026-07-26,2
8,c470e0f78ce2e1b2aca5c845144f59ba24b5bfbee7b62a...,22,22,1,2,[],Austrian Solarindustrie and PV-Wertschöpfungsk...,The Austrian solar industry (Solarindustrie) a...,# Austrian Solarindustrie and PV-Wertschöpfung...,8.0,The impact severity rating is high due to the ...,"[{'explanation': 'The Austrian Solarindustrie,...","{\n ""title"": ""Austrian Solarindustrie and P...",2026-07-26,2
9,a25ffc1b527d0cb3252e8e7d6f0c1b4d541ce26aeb7107...,23,23,1,3,[],Austrian Unternehmen and the EU-Taxonomy Susta...,This community centers around Austrian Unterne...,# Austrian Unternehmen and the EU-Taxonomy Sus...,8.0,The community is rated highly impactful due to...,"[{'explanation': ""Austrian corporate entities ...","{\n ""title"": ""Austrian Unternehmen and the ...",2026-07-26,3
10,40f1882a2d072ab7ac07360120fab7a734fb2b72f81903...,24,24,1,3,[],"European Union Green Policy Community: EU, Mem...",This report covers the core community at the h...,"# European Union Green Policy Community: EU, M...",9.0,The impact severity rating is high because thi...,"[{'explanation': ""The EU stands at the apex of...","{\n ""title"": ""European Union Green Policy C...",2026-07-26,4
11,629180e7b1fb7deff1068387503c2aa7af896ee9bca48a...,25,25,1,3,[],Austria Renewable Energy Technologies: Erneuer...,This report analyzes Austria's renewable energ...,# Austria Renewable Energy Technologies: Erneu...,8.5,The community holds high strategic importance ...,"[{'explanation': 'Erneuerbare Energien, encomp...","{\n ""title"": ""Austria Renewable Energy Tech...",2026-07-26,3
12,0466f1ed2addd214dcd83a5547261018a7e0aad2087b27...,26,26,1,3,[],European PV-System Value Chain,This community centers on the relationship bet...,# European PV-System Value Chain\n\nThis commu...,7.0,The community's importance is high because PV-...,"[{'explanation': 'PV-Systems, or photovoltaic ...","{\n ""title"": ""European PV-System Value Chai...",2026-07-26,2
13,f4ef573b3b8f0af59653a17f7e5016caccc5ef4a4a19f6...,27,27,1,4,[],EU Climate Policy Leadership: European Commiss...,This community is centered around the EU’s amb...,# EU Climate Policy Leadership: European Commi...,8.5,The impact severity rating is high due to the ...,"[{'explanation': ""The 'Fit für 55' package rep...","{\n ""title"": ""EU Climate Policy Leadership:...",2026-07-26,8
14,4ca815914f6db5b2ce7e694255028d84896c8c6a271d85...,28,28,1,4,[],European Union Climate and Energy Policy Decis...,This community centers around the pivotal enti...,# European Union Climate and Energy Policy Dec...,9.0,The impact severity rating is high because thi...,"[{'explanation': ""Brussels is recognized as th...","{\n ""title"": ""European Union Climate and En...",2026-07-26,4
15,e29f0c31350a3632d38d0235900c9517d42eb16520f875...,29,29,1,5,[60 61],Austrian Photovoltaic Strategy and National PV...,This report assesses the Austrian Photovoltaic...,# Austrian Photovoltaic Strategy and National ...,8.7,The impact severity rating is high due to the ...,[{'explanation': 'The Österreichische Photovol...,"{\n ""title"": ""Austrian Photovoltaic Strateg...",2026-07-26,13
16,da3d96f551360d6540b92f36b64d942f7fb86ec7c8c086...,30,30,1,5,[],ÖGUT and Social Innovation Methods in Austria’...,This community focuses on ÖGUT (Austrian Socie...,# ÖGUT and Social Innovation Methods in Austri...,7.0,The community has high strategic significance ...,[{'explanation': 'ÖGUT acts as a hub for docum...,"{\n ""title"": ""ÖGUT and Social Innovation Me...",2026-07-26,2
17,ae34d7c31e9b7b796a747962dbd80c379631f3408b058f...,31,31,1,5,[],Austria’s Photovoltaic Transition Community: W...,This community encompasses Austria's strategic...,# Austria’s Photovoltaic Transition Community:...,8.5,The community’s impact is rated very high due ...,[{'explanation': 'The Wohnungseigentumsgesetz ...,"{\n ""title"": ""Austria’s Photovoltaic Transi...",2026-07-26,5
18,a30ae08d9b6bae8ea2fdcd6827f8e55244d3a66a3f012f...,32,32,1,5,[],BNE e.V. and Biodiversity PV Installations in ...,This community is centered around the Bundesve...,# BNE e.V. and Biodiversity PV Installations i...,8.5,The severity rating reflects the community's s...,[{'explanation': 'The Bundesverband Neue Energ...,"{\n ""title"": ""BNE e.V. and Biodiversity PV ...",2026-07-26,6
19,c3156290fea1560bce321bb33795d0955a1978f9415f3a...,33,33,1,5,[],Austria Renewable Energy Legal & Strategic Fra...,This community is centered on Austria’s ambiti...,# Austria Renewable Energy Legal & Strategic F...,9.0,The community’s entities and relationships are...,[{'explanation': 'The Erneuerbaren-Ausbau-Gese...,"{\n ""title"": ""Austria Renewable Energy Lega...",2026-07-26,4

## 11. Source documents

In [34]:
view("08_documents_all.csv", rows=20)

08_documents_all.csv
Rows: 1
Columns: 7

Column names:
['id', 'human_readable_id', 'title', 'text', 'text_unit_ids', 'creation_date', 'raw_data']

,id,human_readable_id,title,text,text_unit_ids,creation_date,raw_data
0,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,0,AT_STRATEGY_Austrian_Photovoltaic_Strategy_202...,Österreichische Photovoltaik-\nStrategie\n\nZi...,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,2026-07-26 22:20:50 +0200,NaN

## 12. Text units / chunks

In [35]:
view("09_text_units_all.csv", rows=20)

09_text_units_all.csv
Rows: 17
Columns: 8

Column names:
['id', 'human_readable_id', 'text', 'n_tokens', 'document_id', 'entity_ids', 'relationship_ids', 'covariate_ids']

,id,human_readable_id,text,n_tokens,document_id,entity_ids,relationship_ids,covariate_ids
0,d7219f76b31818b7b13bf08dda81003d752e53f7660831...,0,Österreichische Photovoltaik-\nStrategie\n\nZi...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '822...,['ee487943-e36d-4146-8e2e-b7a9a1fd3067'\n 'e87...,[]
1,50fb8f6506c2271985ee7ffe42523d2eb06abbd85be8ea...,1,\n\n6.4.1 Maßnahmen ............................,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['05c9af58-ac32-4ec6-b923-358b587e8cae'\n 'a90...,['0a7b5893-ad12-483f-81b2-a48bcabd624e'\n '5fd...,[]
2,50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e32...,2,"Im Jahr 2023 waren 6,3 TWh er-\n\nreicht.\n\n...",1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['05c9af58-ac32-4ec6-b923-358b587e8cae'\n 'a90...,['1135fa09-924a-4fd4-ad10-3895fb2dee28'\n '71d...,[]
3,e498566a78d36b3ce13304157993b9b4269045840f1d63...,3,"energie, Wasserkraft, Wind- und\n\nBioenergie ...",1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n 'cb0...,['c2727a60-8f2d-4b7f-9fd0-25cd463e97c7'\n 'c27...,[]
4,f9e54ba797ff2b80a5f0e5f24e3901236ac4130e4e84d0...,4,ein Exportschlager der heimischen\n\nWirts...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '05c...,['c2727a60-8f2d-4b7f-9fd0-25cd463e97c7'\n 'e30...,[]
5,06c273ec9919eb4693462fdacebd50536ccdcf47bacc47...,5,langfristige Wirtschaftlichkeit und die Marktk...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '05c...,['aa4a8c35-ffc8-48fa-b27d-77ef5e571f99'\n '9a4...,[]
6,23663988970639bea940978ccbd9150fd292856f2f31a1...,6,"bevorzugte PV-An-\n\nwendungen, sowie eine Au...",1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '37e...,['78386c17-ce06-4ac9-9b9a-fffa45df213e'\n 'b46...,[]
7,41bd25afdc1cce74b36dd6db5e44e91354172fda16475a...,7,ierungszie-\nlen der EU9. Im Bereich der Landw...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['05c9af58-ac32-4ec6-b923-358b587e8cae'\n 'a90...,['fc9dc79a-d096-49c9-b8c3-1e14e447409f'\n '816...,[]
8,6a1a5132f360531b1174e0eac2b2c5b6ece3b0771a8037...,8,sorgung). Trans-\n\nparente Qualitätsauszeichn...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '05c...,['b45ce5a6-e552-4510-a31c-6bad6a3a93c0'\n 'a21...,[]
9,2d9fdebd364caf6ea226dc0ee6624e0c2d54fc65848a9c...,9,Ein Export der PV-Produktion zu erzeugungsstar...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '05c...,['c2727a60-8f2d-4b7f-9fd0-25cd463e97c7'\n '119...,[]
10,4d221520fe7090409cfa9cda598db30683356c340ab358...,10,", um zu klären, ob und in\n\nwelcher Weise ein...",1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '05c...,['0369af84-01bf-4ff5-bf9f-edd6fa8c1fdb'\n '029...,[]
11,7a01190bcf30936758d004f89d7553c62632e91427f92e...,11,den kommenden Jahren bald ein Terawatt (TW) er...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['05c9af58-ac32-4ec6-b923-358b587e8cae'\n 'a90...,['1135fa09-924a-4fd4-ad10-3895fb2dee28'\n '741...,[]
12,9ce049a98570c6bf53cf9e547168db075af2795fa51942...,12,-\n\nropäische PV-Wertschöpfungskette bringt s...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '05c...,['c2727a60-8f2d-4b7f-9fd0-25cd463e97c7'\n '5fd...,[]
13,dafd7f2f39e49c87969ec1360e9fae0af9de6f29065520...,13,"iewende“ hat das\n\nZiel, Lösungen zur Erreich...",1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '05c...,['3ba588af-a743-458d-9c69-44d462e13088'\n '40d...,[]
14,05802f69e17001a506260c74ca400f6a1368fbf0132720...,14,zu jeder Zeit die gesamte Überschussleistung ...,1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '05c...,['c2727a60-8f2d-4b7f-9fd0-25cd463e97c7'\n '7cd...,[]
15,6927535991c09031efd0df39ec21591dd3bb460da14c01...,15,"etz, ersetzt das Elektrizitätswirtschafts- und...",1200,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '00d...,['2d72f58e-a9d3-4cd4-9bc7-e34d517d45d5'\n 'f07...,[]
16,7ae981575e185e2452d144d541d822b7725e27bc7dda50...,16,att\n\nTerawattstunde\n\nUmweltverträglichkeit...,124,39ed356c790f07e222ffe8e84bfb78009537e51e126410...,['cb0a1b84-f9a3-4404-9807-afa3d1e6c3af'\n '822...,['ee487943-e36d-4146-8e2e-b7a9a1fd3067'\n '798...,[]

## 13. Possible duplicate entities

In [36]:
view("10_possible_duplicates.csv", rows=50)

10_possible_duplicates.csv
Rows: 2
Columns: 6

Column names:
['title', 'normalized_title', 'type', 'description', 'frequency', 'degree']

,title,normalized_title,type,description,frequency,degree
0,"FTI-SCHWERPUNKT ""ENERGIEWENDE""",FTI SCHWERPUNKT ENERGIEWENDE,EVENT,"The FTI-Schwerpunkt ""Energiewende"" is a nation...",1,1
1,FTI-SCHWERPUNKT ENERGIEWENDE,FTI SCHWERPUNKT ENERGIEWENDE,EVENT,"The FTI-Schwerpunkt ""Energiewende"" is a resear...",1,2

## 14. Top connected entities

In [37]:
view("11_top_connected_entities.csv", rows=50)

11_top_connected_entities.csv
Rows: 30
Columns: 5

Column names:
['title', 'type', 'degree', 'frequency', 'description']

,title,type,degree,frequency,description
0,ÖSTERREICH,GEO,82,15,"Österreich, also known as Austria, is a Centra..."
1,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,EVENT,39,14,"The ""Österreichische Photovoltaik-Strategie"" (..."
2,PV-ANLAGE,ORGANIZATION,20,3,PV-ANLAGE (Photovoltaic system) refers to dece...
3,BMK,ORGANIZATION,16,7,"BMK, the commonly used abbreviation for the Au..."
4,BUND,ORGANIZATION,14,1,"The federal government of Austria, which colla..."
5,KLIMA- UND ENERGIEFONDS,ORGANIZATION,14,6,The **KLIMA- UND ENERGIEFONDS** (Climate and E...
6,ENERGIEGEMEINSCHAFTEN,ORGANIZATION,14,6,ENERGIEGEMEINSCHAFTEN (energy communities) are...
7,PHOTOVOLTAIKANLAGEN,ORGANIZATION,13,2,Photovoltaikanlagen (Photovoltaic Installation...
8,E-CONTROL,ORGANIZATION,11,6,E-CONTROL is the official Austrian regulatory ...
9,BUNDESLÄNDER,GEO,11,4,"The ""Bundesländer"" are the federal states with..."
10,EUROPÄISCHE KOMMISSION,ORGANIZATION,9,2,"The EUROPÄISCHE KOMMISSION, also known as the ..."
11,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",ORGANIZATION,9,2,"The ""Bundesministerium für Klimaschutz, Umwelt..."
12,EU,ORGANIZATION,8,3,The European Union (EU) is a political and eco...
13,WIEN,GEO,8,3,"WIEN is the German name for Vienna, the capita..."
14,BUNDESVERBAND PV AUSTRIA,ORGANIZATION,7,1,An Austrian federal association representing t...
15,PV-ANLAGEN,EVENT,7,2,"PV-ANLAGEN refers to the deployment, installat..."
16,ENERGIEWENDE,EVENT,6,7,"The ""Energiewende"" in Austria refers to the na..."
17,PHOTOVOLTAIK-STRATEGIE,EVENT,6,1,Die österreichische Photovoltaik-Strategie ist...
18,STROMNETZ,ORGANIZATION,6,1,The public electricity grid (Stromnetz) in Aus...
19,INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTRUKTU...,ORGANIZATION,6,4,The INTEGRIERTER ÖSTERREICHISCHER NETZINFRASTR...
20,PV-INDUSTRIE,ORGANIZATION,5,2,PV-INDUSTRIE refers to the photovoltaic indust...
21,PHOTOVOLTAIK,EVENT,5,2,PHOTOVOLTAIK refers to the deployment and expa...
22,"HACKNER, JOHANNES",PERSON,5,2,Johannes Hackner is an individual recognized f...
23,PV AUSTRIA,ORGANIZATION,5,2,PV Austria is an organization dedicated to pro...
24,ANREIZE UND FÖRDERUNGEN,EVENT,5,1,Anreize und Förderungen (incentives and subsid...
25,WISSENSCHAFT,ORGANIZATION,5,2,WISSENSCHAFT refers to Austria’s scientific co...
26,ERNEUERBAREN-AUSBAU-GESETZ (EAG),EVENT,5,2,"The ERNEUERBAREN-AUSBAU-GESETZ (EAG), known in..."
27,ERNEUERBAREN-AUSBAU-GESETZ,ORGANIZATION,5,1,"The Austrian Renewable Expansion Act (""Erneuer..."
28,WU WIEN,ORGANIZATION,5,2,Vienna University of Economics and Business (W...
29,UNI KLAGENFURT,ORGANIZATION,5,2,"UNI KLAGENFURT, also known as the University o..."

## 15. Top relationships

In [38]:
view("12_top_relationships.csv", rows=50)

12_top_relationships.csv
Rows: 50
Columns: 4

Column names:
['source', 'target', 'description', 'weight']

,source,target,description,weight
0,ÖSTERREICH,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ÖSTERREICH (Austria) is both the creator and p...,67.0
1,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ÖSTERREICH,"The ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE, al...",34.0
2,ÖSTERREICH,BUNDESLÄNDER,"ÖSTERREICH, also known as Austria, is divided ...",33.0
3,BMK,ÖSTERREICH,"BMK, or the Federal Ministry for Climate Actio...",27.0
4,ENERGIEWENDE,ÖSTERREICH,The Energiewende is a major strategic initiati...,19.0
5,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,"The BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT,...",19.0
6,ÖSTERREICH,KLIMANEUTRALITÄT 2040,Austria (ÖSTERREICH) has established an ambiti...,19.0
7,EUROPÄISCHE UNION,ÖSTERREICH,Austria (ÖSTERREICH) is a member state of the ...,18.0
8,E-CONTROL,ÖSTERREICH,E-Control is Austria’s national regulatory aut...,18.0
9,ÖSTERREICH,EU,"ÖSTERREICH, or Austria, is a member state of t...",17.0
10,BÜRGER:INNEN,ENERGIEGEMEINSCHAFTEN,"BÜRGER:INNEN, or citizens, are central partici...",17.0
11,BIODIVERSITÄTS-SOLARPARKS,FREIFLÄCHEN-BIODIVERSITÄTSANLAGEN,Biodiversitäts-Solarparks and Freiflächen-Biod...,16.0
12,EUROPÄISCHE KOMMISSION,FIT FÜR 55,"The European Commission introduced the ""Fit fü...",16.0
13,BUNDESLÄNDER,PV-ANLAGE,"The BUNDESLÄNDER, which are the federal states...",16.0
14,AKTIVER KUNDE,PV-ANLAGE,AKTIVER KUNDE refers to active customers who a...,16.0
15,GEMEINDE,ÖSTERREICH,"In Austria, ""Gemeinden,"" or municipalities, fu...",16.0
16,WIRTSCHAFT,ÖSTERREICH,WIRTSCHAFT and ÖSTERREICH are closely intercon...,15.0
17,PV-ANLAGE,FACHKRÄFTE,PV-ANLAGE (photovoltaic systems) are installed...,15.0
18,PV-ANLAGE,HANDWERKSBETRIEBE,PV-Anlagen (photovoltaic systems) require skil...,15.0
19,KLIMA- UND ENERGIEFONDS,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,The Klima- und Energiefonds (Climate and Energ...,15.0
20,ÖSTERREICH,ENERGIEGEMEINSCHAFTEN,ÖSTERREICH (Austria) has implemented the conce...,15.0
21,PV-ANLAGE,AGRI-PV-ANLAGEN,"PV-ANLAGE refers to photovoltaic systems, comm...",15.0
22,PV-ANLAGE,BIODIVERSITÄTS-SOLARPARKS,PV-ANLAGE refers to photovoltaic systems desig...,14.0
23,PV-ANLAGE,FREIFLÄCHEN-BIODIVERSITÄTSANLAGEN,PV-ANLAGE refers to photovoltaic installations...,14.0
24,PV-ANLAGE,SOLARINDUSTRIE,"The Austrian solar industry, also referred to ...",14.0
25,BMK,P. BIERMAYR,BMK is recognized as the publisher of a market...,14.0
26,FORSCHUNGSEINRICHTUNGEN,ÖSTERREICH,Research institutions in Austria (FORSCHUNGSEI...,14.0
27,PV-ANLAGE,ENERGIEGEMEINSCHAFTEN,PV-Anlagen are widely used within energy commu...,14.0
28,E-CONTROL,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,E-CONTROL plays a significant role in the impl...,13.0
29,EPOOL,PV AUSTRIA,EPOOL and PV Austria are both recognized as co...,12.0
30,BIOENERGIE,WINDENERGIE,BIOENERGIE and WINDENERGIE are both vital rene...,11.0
31,BIOENERGIE,WASSERKRAFT,"BIOENERGIE and WASSERKRAFT, known respectively...",11.0
32,BMK,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...","BMK, which stands for BUNDESMINISTERIUM FÜR KL...",11.0
33,BMK,SERVICEBUERO@BMK.GV.AT,BMK uses servicebuero@bmk.gv.at as its officia...,10.0
34,BMK,BMK.GV.AT,BMK uses bmk.gv.at as its official website or ...,10.0
35,LEONORE GEWESSLER,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",Leonore Gewessler is the Federal Minister lead...,10.0
36,KLIMANEUTRALITÄT 2040,ÖSTERREICH,Klimaneutralität 2040 ist das erklärte Ziel vo...,10.0
37,PHOTOVOLTAIK,ÖSTERREICH,The expansion and use of photovoltaic systems ...,10.0
38,UMWELTBUNDESAMT,TRANSITION 2040,Umweltbundesamt is responsible for the creatio...,10.0
39,PHOTOVOLTAIKANLAGEN,ÖSTERREICH,Photovoltaic installations contribute signific...,10.0
40,EU,ENERGY PERFORMANCE OF BUILDINGS DIRECTIVE,The EU issues the Energy Performance of Buildi...,10.0
41,ÖSTERREICH,BUND,The Bund serves as the federal government of A...,10.0
42,BMK,STAKEHOLDERRUNDEN DES BMK,BMK organized rounds of discussions (stakehold...,10.0
43,IEA PHOTOVOLTAIC POWER SYSTEMS PROGRAMME (PVPS),INTERNATIONALE ENERGIEAGENTUR (IEA),The PVPS is a specific collaborative project o...,10.0
44,PV-ANLAGEN,ÖSTERREICH,PV-Anlagen are being built throughout Austria ...,10.0
45,BUNDESREGIERUNG,NATIONALER FTI-PAKT,The Austrian Federal Government is the issuer ...,10.0
46,ÖSTERREICH,ÖSTERREICHISCHE PV-INDUSTRIE,Austria’s PV industry is central to its effort...,10.0
47,ERNNEUERBAREN-BESCHLEUNIGUNGSGEBIETE (RENEWABL...,RED III,Renewables Acceleration Areas are mandated und...,10.0
48,PHOTOVOLTAIK-STRATEGIE,PHOTOVOLTAIK-AUSBAU,Die Strategie steuert und begleitet den Ausbau...,10.0
49,PHOTOVOLTAIK-STRATEGIE,ÖSTERREICH,Die Photovoltaik-Strategie bildet den Rahmen f...,10.0

## 16. Community report review

In [39]:
view("13_community_report_review.csv", rows=30)

13_community_report_review.csv
Rows: 62
Columns: 18

Column names:
['id', 'human_readable_id', 'community', 'level', 'parent', 'children', 'title', 'summary', 'full_content', 'rank', 'rating_explanation', 'findings', 'full_content_json', 'period', 'size', 'source_supported', 'possible_overgeneralization', 'review_notes']

,id,human_readable_id,community,level,parent,children,title,summary,full_content,rank,rating_explanation,findings,full_content_json,period,size,source_supported,possible_overgeneralization,review_notes
0,a13b29e2a420bd349c8f9109e6022a7eff9c597d717531...,60,60,2,29,[],Austrian Federal Government and National PV De...,This community centers on the Austrian Federal...,# Austrian Federal Government and National PV ...,8.0,The impact severity rating is high because the...,[{'explanation': 'The Austrian Federal Governm...,"{\n ""title"": ""Austrian Federal Government a...",2026-07-26,2,NaN,NaN,NaN
1,26230d3544d875be82557e5e8a2d80bb6e50c105db077b...,61,61,2,29,[],Austrian Photovoltaic Strategy Leadership and ...,This community centers around Austria's nation...,# Austrian Photovoltaic Strategy Leadership an...,8.5,The community commands high impact due to its ...,"[{'explanation': 'The ""Österreichische Photovo...","{\n ""title"": ""Austrian Photovoltaic Strateg...",2026-07-26,11,NaN,NaN,NaN
2,4cfc69a997bb9b15ad32bfa02086d886bfddcb1f76ce50...,16,16,1,0,[],E-Control and Austria's Grid Connection Action...,"This community centers on E-Control, Austria’s...",# E-Control and Austria's Grid Connection Acti...,8.5,The impact severity rating is high due to E-Co...,"[{'explanation': ""E-Control occupies a central...","{\n ""title"": ""E-Control and Austria's Grid ...",2026-07-26,6,NaN,NaN,NaN
3,003b89cc2b10773b1215b9f1c80d85aace49d6e3a4795f...,17,17,1,0,[],Austria’s Photovoltaic and Energy Transition S...,This community comprises key Austrian institut...,# Austria’s Photovoltaic and Energy Transition...,8.0,The impact severity rating is high due to the ...,[{'explanation': 'BMK (the Austrian Federal Mi...,"{\n ""title"": ""Austria’s Photovoltaic and En...",2026-07-26,9,NaN,NaN,NaN
4,6c92ae3c680eb80aff4de648ad303a3d98042d7efd5516...,18,18,1,0,[],Austrian Federal Ministry for Climate Action a...,This community centers around Austria's Federa...,# Austrian Federal Ministry for Climate Action...,8.5,The BMK community poses high impact due to its...,"[{'explanation': ""The Bundesministerium für Kl...","{\n ""title"": ""Austrian Federal Ministry for...",2026-07-26,4,NaN,NaN,NaN
5,e7194ecf611b10a2fb9ba5600ea1208399a1cbe30a57af...,19,19,1,2,[],Austrian Renewable Expansion Act and AGRI-PV-A...,This community centers on the implementation o...,# Austrian Renewable Expansion Act and AGRI-PV...,8.5,The community has a high impact severity ratin...,[{'explanation': 'The Austrian Renewable Expan...,"{\n ""title"": ""Austrian Renewable Expansion ...",2026-07-26,4,NaN,NaN,NaN
6,4517b31e6c628891cde69690d418e600c1c4db5297bac0...,20,20,1,2,[],Austria's Photovoltaic Sector and Energy Marke...,This community centers on Austria’s rapidly ev...,# Austria's Photovoltaic Sector and Energy Mar...,8.5,The severity rating is high due to the communi...,"[{'explanation': 'PV-ANLAGE installations, enc...","{\n ""title"": ""Austria's Photovoltaic Sector...",2026-07-26,12,NaN,NaN,NaN
7,ab32d2277b97f91d2d5732a8f957b8a7b550ef8f66b7e3...,21,21,1,2,[],Austrian Biodiversitäts-Solarpark and Freifläc...,This community encompasses Austria's effort to...,# Austrian Biodiversitäts-Solarpark and Freifl...,8.5,"The community’s integrated, dual-focus approac...",[{'explanation': 'Both FREIFLÄCHEN-BIODIVERSIT...,"{\n ""title"": ""Austrian Biodiversitäts-Solar...",2026-07-26,2,NaN,NaN,NaN
8,c470e0f78ce2e1b2aca5c845144f59ba24b5bfbee7b62a...,22,22,1,2,[],Austrian Solarindustrie and PV-Wertschöpfungsk...,The Austrian solar industry (Solarindustrie) a...,# Austrian Solarindustrie and PV-Wertschöpfung...,8.0,The impact severity rating is high due to the ...,"[{'explanation': 'The Austrian Solarindustrie,...","{\n ""title"": ""Austrian Solarindustrie and P...",2026-07-26,2,NaN,NaN,NaN
9,a25ffc1b527d0cb3252e8e7d6f0c1b4d541ce26aeb7107...,23,23,1,3,[],Austrian Unternehmen and the EU-Taxonomy Susta...,This community centers around Austrian Unterne...,# Austrian Unternehmen and the EU-Taxonomy Sus...,8.0,The community is rated highly impactful due to...,"[{'explanation': ""Austrian corporate entities ...","{\n ""title"": ""Austrian Unternehmen and the ...",2026-07-26,3,NaN,NaN,NaN
10,40f1882a2d072ab7ac07360120fab7a734fb2b72f81903...,24,24,1,3,[],"European Union Green Policy Community: EU, Mem...",This report covers the core community at the h...,"# European Union Green Policy Community: EU, M...",9.0,The impact severity rating is high because thi...,"[{'explanation': ""The EU stands at the apex of...","{\n ""title"": ""European Union Green Policy C...",2026-07-26,4,NaN,NaN,NaN
11,629180e7b1fb7deff1068387503c2aa7af896ee9bca48a...,25,25,1,3,[],Austria Renewable Energy Technologies: Erneuer...,This report analyzes Austria's renewable energ...,# Austria Renewable Energy Technologies: Erneu...,8.5,The community holds high strategic importance ...,"[{'explanation': 'Erneuerbare Energien, encomp...","{\n ""title"": ""Austria Renewable Energy Tech...",2026-07-26,3,NaN,NaN,NaN
12,0466f1ed2addd214dcd83a5547261018a7e0aad2087b27...,26,26,1,3,[],European PV-System Value Chain,This community centers on the relationship bet...,# European PV-System Value Chain\n\nThis commu...,7.0,The community's importance is high because PV-...,"[{'explanation': 'PV-Systems, or photovoltaic ...","{\n ""title"": ""European PV-System Value Chai...",2026-07-26,2,NaN,NaN,NaN
13,f4ef573b3b8f0af59653a17f7e5016caccc5ef4a4a19f6...,27,27,1,4,[],EU Climate Policy Leadership: European Commiss...,This community is centered around the EU’s amb...,# EU Climate Policy Leadership: European Commi...,8.5,The impact severity rating is high due to the ...,"[{'explanation': ""The 'Fit für 55' package rep...","{\n ""title"": ""EU Climate Policy Leadership:...",2026-07-26,8,NaN,NaN,NaN
14,4ca815914f6db5b2ce7e694255028d84896c8c6a271d85...,28,28,1,4,[],European Union Climate and Energy Policy Decis...,This community centers around the pivotal enti...,# European Union Climate and Energy Policy Dec...,9.0,The impact severity rating is high because thi...,"[{'explanation': ""Brussels is recognized as th...","{\n ""title"": ""European Union Climate and En...",2026-07-26,4,NaN,NaN,NaN
15,e29f0c31350a3632d38d0235900c9517d42eb16520f875...,29,29,1,5,[60 61],Austrian Photovoltaic Strategy and National PV...,This report assesses the Austrian Photovoltaic...,# Austrian Photovoltaic Strategy and National ...,8.7,The impact severity rating is high due to the ...,[{'explanation': 'The Österreichische Photovol...,"{\n ""title"": ""Austrian Photovoltaic Strateg...",2026-07-26,13,NaN,NaN,NaN
16,da3d96f551360d6540b92f36b64d942f7fb86ec7c8c086...,30,30,1,5,[],ÖGUT and Social Innovation Methods in Austria’...,This community focuses on ÖGUT (Austrian Socie...,# ÖGUT and Social Innovation Methods in Austri...,7.0,The community has high strategic significance ...,[{'explanation': 'ÖGUT acts as a hub for docum...,"{\n ""title"": ""ÖGUT and Social Innovation Me...",2026-07-26,2,NaN,NaN,NaN
17,ae34d7c31e9b7b796a747962dbd80c379631f3408b058f...,31,31,1,5,[],Austria’s Photovoltaic Transition Community: W...,This community encompasses Austria's strategic...,# Austria’s Photovoltaic Transition Community:...,8.5,The community’s impact is rated very high due ...,[{'explanation': 'The Wohnungseigentumsgesetz ...,"{\n ""title"": ""Austria’s Photovoltaic Transi...",2026-07-26,5,NaN,NaN,NaN
18,a30ae08d9b6bae8ea2fdcd6827f8e55244d3a66a3f012f...,32,32,1,5,[],BNE e.V. and Biodiversity PV Installations in ...,This community is centered around the Bundesve...,# BNE e.V. and Biodiversity PV Installations i...,8.5,The severity rating reflects the community's s...,[{'explanation': 'The Bundesverband Neue Energ...,"{\n ""title"": ""BNE e.V. and Biodiversity PV ...",2026-07-26,6,NaN,NaN,NaN
19,c3156290fea1560bce321bb33795d0955a1978f9415f3a...,33,33,1,5,[],Austria Renewable Energy Legal & Strategic Fra...,This community is centered on Austria’s ambiti...,# Austria Renewable Energy Legal & Strategic F...,9.0,The community’s entities and relationships are...,[{'explanation': 'The Erneuerbaren-Ausbau-Gese...,"{\n ""title"": ""Austria Renewable Energy Lega...",2026-07-26,4,NaN,NaN,NaN
20,80256f2e9cd4097a5b17a7639044ab7e40a0d22dbc6eb9...,34,34,1,5,[],Austrian Noise Barriers and PV Integration in ...,This community focuses on the strategic deploy...,# Austrian Noise Barriers and PV Integration i...,7.5,The impact severity is high due to the potenti...,[{'explanation': 'LÄRMSCHUTZWÄNDE are recogniz...,"{\n ""title"": ""Austrian Noise Barriers and P...",2026-07-26,2,NaN,NaN,NaN
21,87b9a0bbb81d99c0b01c1a4ef5b09e70fd9ec4029480b4...,35,35,1,5,[],Austrian Parking Surfaces and Sealed Areas for...,This community centers around the strategic us...,# Austrian Parking Surfaces and Sealed Areas f...,7.5,The impact severity rating is high due to the ...,[{'explanation': 'Parking areas (Parkplätze) w...,"{\n ""title"": ""Austrian Parking Surfaces and...",2026-07-26,2,NaN,NaN,NaN
22,232a56ad57b2bdc9c01eccf759252c5453d734dc748264...,36,36,1,6,[],Vienna Climate Action Governance and Innovatio...,This community centers around the institutiona...,# Vienna Climate Action Governance and Innovat...,8.5,The community has a high impact due to its cen...,"[{'explanation': ""Vienna (Wien) plays a centra...","{\n ""title"": ""Vienna Climate Action Governa...",2026-07-26,4,NaN,NaN,NaN
23,8306bf073d8bedc14344b765d9e30d80246d3e1640ae7e...,37,37,1,6,[],Austrian Federal Ministry for Climate Action a...,This community is centered around the Austrian...,# Austrian Federal Ministry for Climate Action...,8.5,The community poses a high impact severity due...,[{'explanation': 'The Bundesministerium für Kl...,"{\n ""title"": ""Austrian Federal Ministry for...",2026-07-26,4,NaN,NaN,NaN
24,f7b0f2dae5f7d3cb82865faff3c8a7fe70547a7598df52...,38,38,1,6,[],Austria Photovoltaics Research and Public Opin...,This community is centered on academic and res...,# Austria Photovoltaics Research and Public Op...,8.5,The impact severity rating is high because thi...,[{'explanation': 'Recent studies indicate that...,"{\n ""title"": ""Austria Photovoltaics Researc...",2026-07-26,4,NaN,NaN,NaN
25,6ddb6e0c0728f6a7e4beb1f994b2052308e9d11ab480b0...,39,39,1,6,[],ÖGUT and Social Innovation in Energy Transition,This community report focuses on the collabora...,# ÖGUT and Social Innovation in Energy Transit...,6.5,While this community's efforts have notable po...,[{'explanation': 'ÖGUT stands as a pivotal org...,"{\n ""title"": ""ÖGUT and Social Innovation in...",2026-07-26,2,NaN,NaN,NaN
26,65faa77139d1990d3518c7525228399d24316d2a44d5e9...,40,40,1,8,[],Austrian Climate and Energy Fund & Key Renewab...,This community centers on the Austrian governm...,# Austrian Climate and Energy Fund & Key Renew...,8.5,The high rating reflects the national strategi...,[{'explanation': 'The Klima- und Energiefonds ...,"{\n ""title"": ""Austrian Climate and Energy F...",2026-07-26,5,NaN,NaN,NaN
27,7ad83169641eb9b757138949a2c50a0328341dc1c9d17e...,41,41,1,8,[],"PV Austria, EPOOL, and Johannes Hackner Renewa...","This community revolves around PV Austria, EPO...","# PV Austria, EPOOL, and Johannes Hackner Rene...",8.0,This community holds significant impact due to...,"[{'explanation': ""PV Austria serves as a promi...","{\n ""title"": ""PV Austria, EPOOL, and Johann...",2026-07-26,4,NaN,NaN,NaN
28,a858e2e2bc7bc66a0d4791f7beb6c4fcbbecfc80d6e15a...,42,42,1,8,[],Austrian Grid Operators and Large-Scale Renewa...,This community consists of key actors in Austr...,# Austrian Grid Operators and Large-Scale Rene...,8.5,This community has a high impact on Austria's ...,"[{'explanation': ""Stromnetze, representing Aus...","{\n ""title"": ""Austrian Grid Operators and L...",2026-07-26,3,NaN,NaN,NaN
29,7dce8ce2f676561186ab76f42202016e7cd81f6e932d98...,43,43,1,8,[],PV-Anlagen Community and Austria's Photovoltai...,"This community centers around the deployment, ...",# PV-Anlagen Community and Austria's Photovolt...,8.5,The impact severity rating is high because the...,"[{'explanation': ""PV-ANLAGEN represents the co...","{\n ""title"": ""PV-Anlagen Community and Aust...",2026-07-26,7,NaN,NaN,NaN

## 17. Search entities by word

Change `search_term` to anything you want, for example:
- `photovoltaik`
- `eag`
- `österreich`
- `netz`
- `förder`

In [40]:
search_term = "photovoltaik"

df = datasets["03_entity_review.csv"]

mask = df.astype(str).apply(
    lambda col: col.str.contains(search_term, case=False, na=False)
).any(axis=1)

display(df[mask])

,human_readable_id,title,type,description,frequency,degree,text_unit_ids,suggested_schema_type,canonical_name,keep_in_controlled_kg,record_linkage_group,review_notes
0,0,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,EVENT,"The ""Österreichische Photovoltaik-Strategie"" (...",14,39,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
8,8,PHOTOVOLTAIK (PV),EVENT,The technological process of converting solar ...,1,4,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
9,9,CAJETAN PERWEIN,PERSON,Cajetan Perwein is credited as a photographer ...,1,1,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,NaN,NaN,NaN,NaN,NaN
26,26,PHOTOVOLTAIK-STRATEGIE,EVENT,Die österreichische Photovoltaik-Strategie ist...,1,6,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,NaN,NaN,NaN,NaN,NaN
36,36,PHOTOVOLTAIK-AUSBAU,EVENT,Der Ausbau der Photovoltaik in Österreich ist ...,1,2,['50e06bf07ca2ce3a4e0dc0520305a36334e339dc022e...,NaN,NaN,NaN,NaN,NaN
56,56,PHOTOVOLTAIKANLAGEN,ORGANIZATION,Photovoltaikanlagen (Photovoltaic Installation...,2,13,['f9e54ba797ff2b80a5f0e5f24e3901236ac4130e4e84...,NaN,NaN,NaN,NaN,NaN
66,66,PHOTOVOLTAIK,EVENT,PHOTOVOLTAIK refers to the deployment and expa...,2,5,['06c273ec9919eb4693462fdacebd50536ccdcf47bacc...,NaN,NaN,NaN,NaN,NaN
121,121,MUSTER- & LEUCHTTURMPROJEKTE PHOTOVOLTAIK,EVENT,The Muster- & Leuchtturmprojekte Photovoltaik ...,1,1,['6a1a5132f360531b1174e0eac2b2c5b6ece3b0771a80...,NaN,NaN,NaN,NaN,NaN
161,161,PHOTOVOLTAIK-PROJEKTE,EVENT,Photovoltaic projects are solar power installa...,1,4,['4d221520fe7090409cfa9cda598db30683356c340ab3...,NaN,NaN,NaN,NaN,NaN

## 18. Search relationships by word

Change `search_term` to investigate a topic.

In [41]:
search_term = "photovoltaik"

df = datasets["05_relationship_review.csv"]

mask = df.astype(str).apply(
    lambda col: col.str.contains(search_term, case=False, na=False)
).any(axis=1)

display(df[mask])

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids,source_raw_type,target_raw_type,evidence_status,suggested_relation_type,keep_in_controlled_kg,review_notes
0,ee487943-e36d-4146-8e2e-b7a9a1fd3067,0,"BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT, ENE...",ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,"The BUNDESMINISTERIUM FÜR KLIMASCHUTZ, UMWELT,...",19.0,48,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,ORGANIZATION,EVENT,NaN,NaN,NaN,NaN
1,e87db637-71f3-4134-8a02-954d1e518207,1,HUBERT FECHNER,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Hubert Fechner is the principal author of the ...,8.0,41,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,PERSON,EVENT,NaN,NaN,NaN,NaN
3,86b0f8da-0a86-48c8-990d-8fbbe165249b,3,LEONORE GEWESSLER,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,"Leonore Gewessler represents, promotes, and ov...",9.0,41,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,PERSON,EVENT,NaN,NaN,NaN,NaN
4,c2727a60-8f2d-4b7f-9fd0-25cd463e97c7,4,ÖSTERREICH,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,ÖSTERREICH (Austria) is both the creator and p...,67.0,121,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,GEO,EVENT,NaN,NaN,NaN,NaN
7,34e20a8c-8899-486c-afa6-f1467d515bfb,7,ERNEUERBAREN-AUSBAU-GESETZ (EAG),ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,The EAG is a backbone legal act referenced and...,9.0,44,['d7219f76b31818b7b13bf08dda81003d752e53f76608...,EVENT,EVENT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,c618bc16-f9d2-489c-a04e-cae770590528,345,FIT FÜR 55,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Austria’s photovoltaic policy aligns with the ...,6.0,43,['05802f69e17001a506260c74ca400f6a1368fbf01327...,EVENT,EVENT,NaN,NaN,NaN,NaN
374,b3361593-90d6-4465-9247-addaee363a9b,374,BUNDESVERBAND PV AUSTRIA,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Bundesverband PV Austria is involved in shapin...,6.0,46,['6927535991c09031efd0df39ec21591dd3bb460da14c...,ORGANIZATION,EVENT,NaN,NaN,NaN,NaN
400,ff337f7e-4657-428a-b4d7-d19e98663e83,400,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,PV-ANLAGEN,The PV strategy is developed to advance the in...,9.0,46,['6927535991c09031efd0df39ec21591dd3bb460da14c...,EVENT,EVENT,NaN,NaN,NaN,NaN
405,82d1a5db-4db4-4a29-b7ba-73ad1004cb75,405,UMWELTVERTRÄGLICHKEITSPRÜFUNG,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Environmental impact assessments are a relevan...,6.0,40,['7ae981575e185e2452d144d541d822b7725e27bc7dda...,EVENT,EVENT,NaN,NaN,NaN,NaN
406,7e82baa0-357c-49a1-b326-14aaf135f4c9,406,TERAWATTSTUNDE,ÖSTERREICHISCHE PHOTOVOLTAIK-STRATEGIE,Terawatt-hour is likely a measurement related ...,7.0,40,['7ae981575e185e2452d144d541d822b7725e27bc7dda...,EVENT,EVENT,NaN,NaN,NaN,NaN

## 19. Show a full dataset

Jupyter normally truncates large tables.  
Use the line below for a full dataset when needed.

Be careful: entities have 312 rows and relationships have 414 rows.

In [42]:
# Example:
# display(datasets["03_entity_review.csv"])

# Uncomment the line below when you want the complete entity review table:
# display(datasets["03_entity_review.csv"])

## Recommended inspection order

1. `02_entity_type_counts.csv`
2. `03_entity_review.csv`
3. `10_possible_duplicates.csv`
4. `11_top_connected_entities.csv`
5. `05_relationship_review.csv`
6. `12_top_relationships.csv`
7. `07_community_reports_all.csv`
8. `09_text_units_all.csv`

We will compare the raw GraphRAG output with your Solar Market Schema V1 rather than accepting the raw graph automatically.